return {
	file="lato_regular_14_black.PNG",
	height=22,
	description={
		family="Lato",
		style="Regular",
		size=14
	},
	metrics={
		ascender=19,
		descender=-4,
		height=22
	},
	texture={
		file="lato_regular_14_black.PNG",
		width=223,
		height=225
	},
	chars={
		[" "] = {width=4,x=1,y=17,w=0,h=0,ox=0,oy=0},
		["!"] = {width=7,x=2,y=3,w=3,h=14,ox=2,oy=14},
		['"'] = {width=8,x=6,y=3,w=6,h=5,ox=1,oy=14},
		["#"] = {width=11,x=13,y=3,w=11,h=14,ox=0,oy=14},
		["$"] = {width=11,x=25,y=1,w=10,h=18,ox=1,oy=16},
		["%"] = {width=15,x=36,y=3,w=15,h=14,ox=0,oy=14},
		["&"] = {width=13,x=52,y=3,w=14,h=14,ox=0,oy=14},
		["'"] = {width=4,x=67,y=3,w=2,h=5,ox=1,oy=14},
		["("] = {width=6,x=70,y=1,w=4,h=19,ox=1,oy=16},
		[")"] = {width=6,x=75,y=1,w=5,h=19,ox=0,oy=16},
		["*"] = {width=8,x=81,y=3,w=7,h=6,ox=0,oy=14},
		["+"] = {width=11,x=89,y=5,w=11,h=10,ox=0,oy=12},
		[","] = {width=4,x=101,y=14,w=4,h=6,ox=0,oy=3},
		["-"] = {width=7,x=106,y=10,w=6,h=3,ox=0,oy=7},
		["."] = {width=4,x=113,y=14,w=4,h=3,ox=0,oy=3},
		["/"] = {width=7,x=118,y=3,w=9,h=15,ox=-1,oy=14},
		["0"] = {width=11,x=128,y=3,w=11,h=14,ox=0,oy=14},
		["1"] = {width=11,x=140,y=3,w=10,h=14,ox=1,oy=14},
		["2"] = {width=11,x=151,y=3,w=11,h=14,ox=0,oy=14},
		["3"] = {width=11,x=163,y=3,w=10,h=14,ox=1,oy=14},
		["4"] = {width=11,x=174,y=3,w=11,h=14,ox=0,oy=14},
		["5"] = {width=11,x=186,y=3,w=9,h=14,ox=1,oy=14},
		["6"] = {width=11,x=196,y=3,w=10,h=14,ox=1,oy=14},
		["7"] = {width=11,x=207,y=3,w=10,h=14,ox=1,oy=14},
		["8"] = {width=11,x=1,y=21,w=11,h=14,ox=0,oy=14},
		["9"] = {width=11,x=13,y=21,w=10,h=14,ox=1,oy=14},
		[":"] = {width=5,x=24,y=25,w=3,h=10,ox=1,oy=10},
		[";"] = {width=5,x=28,y=25,w=3,h=13,ox=1,oy=10},
		["<"] = {width=11,x=32,y=24,w=8,h=9,ox=1,oy=11},
		["="] = {width=11,x=41,y=25,w=9,h=6,ox=1,oy=10},
		[">"] = {width=11,x=51,y=24,w=8,h=9,ox=2,oy=11},
		["?"] = {width=8,x=60,y=21,w=8,h=14,ox=0,oy=14},
		["@"] = {width=16,x=69,y=21,w=15,h=17,ox=0,oy=14},
		["A"] = {width=13,x=85,y=21,w=13,h=14,ox=0,oy=14},
		["B"] = {width=12,x=99,y=21,w=11,h=14,ox=1,oy=14},
		["C"] = {width=13,x=111,y=21,w=13,h=14,ox=0,oy=14},
		["D"] = {width=14,x=125,y=21,w=13,h=14,ox=1,oy=14},
		["E"] = {width=11,x=139,y=21,w=10,h=14,ox=1,oy=14},
		["F"] = {width=11,x=150,y=21,w=10,h=14,ox=1,oy=14},
		["G"] = {width=14,x=161,y=21,w=13,h=14,ox=0,oy=14},
		["H"] = {width=14,x=175,y=21,w=12,h=14,ox=1,oy=14},
		["I"] = {width=6,x=188,y=21,w=2,h=14,ox=2,oy=14},
		["J"] = {width=8,x=191,y=21,w=7,h=14,ox=0,oy=14},
		["K"] = {width=13,x=199,y=21,w=12,h=14,ox=1,oy=14},
		["L"] = {width=10,x=212,y=21,w=9,h=14,ox=1,oy=14},
		["M"] = {width=17,x=1,y=40,w=15,h=14,ox=1,oy=14},
		["N"] = {width=14,x=17,y=40,w=12,h=14,ox=1,oy=14},
		["O"] = {width=15,x=30,y=40,w=15,h=14,ox=0,oy=14},
		["P"] = {width=12,x=46,y=40,w=10,h=14,ox=1,oy=14},
		["Q"] = {width=15,x=57,y=40,w=15,h=17,ox=0,oy=14},
		["R"] = {width=12,x=73,y=40,w=11,h=14,ox=1,oy=14},
		["S"] = {width=10,x=85,y=40,w=10,h=14,ox=0,oy=14},
		["T"] = {width=11,x=96,y=40,w=11,h=14,ox=0,oy=14},
		["U"] = {width=14,x=108,y=40,w=12,h=14,ox=1,oy=14},
		["V"] = {width=13,x=121,y=40,w=13,h=14,ox=0,oy=14},
		["W"] = {width=19,x=135,y=40,w=20,h=14,ox=0,oy=14},
		["X"] = {width=12,x=156,y=40,w=13,h=14,ox=0,oy=14},
		["Y"] = {width=12,x=170,y=40,w=12,h=14,ox=0,oy=14},
		["Z"] = {width=12,x=183,y=40,w=12,h=14,ox=0,oy=14},
		["["] = {width=6,x=196,y=39,w=4,h=19,ox=1,oy=15},
		["\\"] = {width=7,x=201,y=40,w=9,h=15,ox=-1,oy=14},
		["]"] = {width=6,x=211,y=39,w=5,h=19,ox=0,oy=15},
		["^"] = {width=11,x=1,y=59,w=9,h=7,ox=1,oy=14},
		["_"] = {width=7,x=11,y=74,w=8,h=3,ox=0,oy=-1},
		["`"] = {width=6,x=20,y=59,w=5,h=3,ox=0,oy=14},
		["a"] = {width=10,x=26,y=63,w=9,h=10,ox=0,oy=10},
		["b"] = {width=11,x=36,y=59,w=9,h=14,ox=1,oy=14},
		["c"] = {width=9,x=46,y=63,w=9,h=10,ox=0,oy=10},
		["d"] = {width=11,x=56,y=59,w=10,h=14,ox=0,oy=14},
		["e"] = {width=10,x=67,y=63,w=10,h=10,ox=0,oy=10},
		["f"] = {width=6,x=78,y=59,w=7,h=14,ox=0,oy=14},
		["g"] = {width=10,x=86,y=63,w=10,h=13,ox=0,oy=10},
		["h"] = {width=11,x=97,y=59,w=9,h=14,ox=1,oy=14},
		["i"] = {width=5,x=107,y=59,w=3,h=14,ox=1,oy=14},
		["j"] = {width=5,x=111,y=59,w=5,h=17,ox=-1,oy=14},
		["k"] = {width=10,x=117,y=59,w=9,h=14,ox=1,oy=14},
		["l"] = {width=5,x=127,y=59,w=3,h=14,ox=1,oy=14},
		["m"] = {width=16,x=131,y=63,w=14,h=10,ox=1,oy=10},
		["n"] = {width=11,x=146,y=63,w=9,h=10,ox=1,oy=10},
		["o"] = {width=11,x=156,y=63,w=10,h=10,ox=0,oy=10},
		["p"] = {width=10,x=167,y=63,w=9,h=13,ox=1,oy=10},
		["q"] = {width=11,x=177,y=63,w=10,h=13,ox=0,oy=10},
		["r"] = {width=8,x=188,y=63,w=7,h=10,ox=1,oy=10},
		["s"] = {width=8,x=196,y=63,w=8,h=10,ox=0,oy=10},
		["t"] = {width=7,x=205,y=60,w=7,h=13,ox=0,oy=13},
		["u"] = {width=11,x=1,y=83,w=9,h=10,ox=1,oy=10},
		["v"] = {width=10,x=11,y=83,w=10,h=10,ox=0,oy=10},
		["w"] = {width=15,x=22,y=83,w=15,h=10,ox=0,oy=10},
		["x"] = {width=10,x=38,y=83,w=10,h=10,ox=0,oy=10},
		["y"] = {width=10,x=49,y=83,w=10,h=13,ox=0,oy=10},
		["z"] = {width=9,x=60,y=83,w=9,h=10,ox=0,oy=10},
		["{"] = {width=6,x=70,y=78,w=5,h=19,ox=0,oy=15},
		["|"] = {width=6,x=76,y=78,w=2,h=18,ox=2,oy=15},
		["}"] = {width=6,x=79,y=78,w=6,h=19,ox=0,oy=15},
		["~"] = {width=11,x=86,y=85,w=9,h=4,ox=1,oy=8},
		["¡"] = {width=7,x=96,y=83,w=3,h=13,ox=2,oy=10},
		["¢"] = {width=11,x=100,y=80,w=9,h=15,ox=1,oy=13},
		["£"] = {width=11,x=110,y=79,w=11,h=14,ox=0,oy=14},
		["¤"] = {width=11,x=122,y=82,w=9,h=10,ox=1,oy=11},
		["¥"] = {width=11,x=132,y=79,w=11,h=14,ox=0,oy=14},
		["¦"] = {width=6,x=144,y=78,w=2,h=18,ox=2,oy=15},
		["§"] = {width=10,x=147,y=79,w=8,h=16,ox=1,oy=14},
		["¨"] = {width=6,x=156,y=79,w=6,h=3,ox=0,oy=14},
		["©"] = {width=15,x=163,y=79,w=15,h=14,ox=0,oy=14},
		["ª"] = {width=7,x=179,y=79,w=6,h=7,ox=0,oy=14},
		["«"] = {width=9,x=186,y=83,w=7,h=9,ox=1,oy=10},
		["¬"] = {width=11,x=194,y=85,w=9,h=6,ox=1,oy=8},
		["­"] = {width=7,x=204,y=86,w=6,h=3,ox=0,oy=7},
		["®"] = {width=15,x=1,y=102,w=15,h=14,ox=0,oy=14},
		["¯"] = {width=6,x=17,y=102,w=6,h=3,ox=0,oy=14},
		["°"] = {width=8,x=24,y=102,w=7,h=7,ox=0,oy=14},
		["±"] = {width=11,x=32,y=104,w=11,h=12,ox=0,oy=12},
		["²"] = {width=6,x=44,y=99,w=6,h=9,ox=0,oy=17},
		["³"] = {width=6,x=51,y=99,w=6,h=9,ox=0,oy=17},
		["´"] = {width=6,x=58,y=102,w=5,h=3,ox=1,oy=14},
		["µ"] = {width=11,x=64,y=106,w=9,h=13,ox=1,oy=10},
		["¶"] = {width=13,x=74,y=102,w=13,h=16,ox=0,oy=14},
		["·"] = {width=5,x=88,y=109,w=4,h=3,ox=1,oy=7},
		["¸"] = {width=6,x=93,y=115,w=4,h=4,ox=1,oy=1},
		["¹"] = {width=6,x=98,y=100,w=5,h=8,ox=1,oy=16},
		["º"] = {width=7,x=104,y=102,w=7,h=7,ox=0,oy=14},
		["»"] = {width=9,x=112,y=106,w=7,h=9,ox=1,oy=10},
		["¼"] = {width=14,x=120,y=102,w=14,h=14,ox=0,oy=14},
		["½"] = {width=14,x=135,y=102,w=14,h=14,ox=0,oy=14},
		["¾"] = {width=14,x=150,y=102,w=14,h=14,ox=0,oy=14},
		["¿"] = {width=8,x=165,y=106,w=8,h=13,ox=0,oy=10},
		["À"] = {width=13,x=174,y=98,w=13,h=18,ox=0,oy=18},
		["Á"] = {width=13,x=188,y=98,w=13,h=18,ox=0,oy=18},
		["Â"] = {width=13,x=202,y=99,w=13,h=17,ox=0,oy=17},
		["Ã"] = {width=13,x=1,y=120,w=13,h=18,ox=0,oy=18},
		["Ä"] = {width=13,x=15,y=120,w=13,h=18,ox=0,oy=18},
		["Å"] = {width=13,x=29,y=120,w=13,h=18,ox=0,oy=18},
		["Æ"] = {width=18,x=43,y=124,w=18,h=14,ox=-1,oy=14},
		["Ç"] = {width=13,x=62,y=124,w=13,h=17,ox=0,oy=14},
		["È"] = {width=11,x=76,y=120,w=10,h=18,ox=1,oy=18},
		["É"] = {width=11,x=87,y=120,w=10,h=18,ox=1,oy=18},
		["Ê"] = {width=11,x=98,y=121,w=10,h=17,ox=1,oy=17},
		["Ë"] = {width=11,x=109,y=120,w=10,h=18,ox=1,oy=18},
		["Ì"] = {width=6,x=120,y=120,w=6,h=18,ox=-1,oy=18},
		["Í"] = {width=6,x=127,y=120,w=6,h=18,ox=1,oy=18},
		["Î"] = {width=6,x=134,y=121,w=7,h=17,ox=-1,oy=17},
		["Ï"] = {width=6,x=142,y=120,w=7,h=18,ox=-1,oy=18},
		["Ð"] = {width=15,x=150,y=124,w=15,h=14,ox=0,oy=14},
		["Ñ"] = {width=14,x=166,y=120,w=12,h=18,ox=1,oy=18},
		["Ò"] = {width=15,x=179,y=120,w=15,h=18,ox=0,oy=18},
		["Ó"] = {width=15,x=195,y=120,w=15,h=18,ox=0,oy=18},
		["Ô"] = {width=15,x=1,y=143,w=15,h=17,ox=0,oy=17},
		["Õ"] = {width=15,x=17,y=142,w=15,h=18,ox=0,oy=18},
		["Ö"] = {width=15,x=33,y=142,w=15,h=18,ox=0,oy=18},
		["×"] = {width=11,x=49,y=149,w=9,h=9,ox=1,oy=11},
		["Ø"] = {width=15,x=59,y=146,w=15,h=15,ox=0,oy=14},
		["Ù"] = {width=14,x=75,y=142,w=12,h=18,ox=1,oy=18},
		["Ú"] = {width=14,x=88,y=142,w=12,h=18,ox=1,oy=18},
		["Û"] = {width=14,x=101,y=143,w=12,h=17,ox=1,oy=17},
		["Ü"] = {width=14,x=114,y=142,w=12,h=18,ox=1,oy=18},
		["Ý"] = {width=12,x=127,y=142,w=12,h=18,ox=0,oy=18},
		["Þ"] = {width=12,x=140,y=146,w=10,h=14,ox=1,oy=14},
		["ß"] = {width=12,x=151,y=146,w=10,h=14,ox=1,oy=14},
		["à"] = {width=10,x=162,y=146,w=9,h=14,ox=0,oy=14},
		["á"] = {width=10,x=172,y=146,w=9,h=14,ox=0,oy=14},
		["â"] = {width=10,x=182,y=146,w=9,h=14,ox=0,oy=14},
		["ã"] = {width=10,x=192,y=146,w=9,h=14,ox=0,oy=14},
		["ä"] = {width=10,x=202,y=146,w=9,h=14,ox=0,oy=14},
		["å"] = {width=10,x=212,y=146,w=9,h=14,ox=0,oy=14},
		["æ"] = {width=16,x=1,y=166,w=15,h=10,ox=0,oy=10},
		["ç"] = {width=9,x=17,y=166,w=9,h=13,ox=0,oy=10},
		["è"] = {width=10,x=27,y=162,w=10,h=14,ox=0,oy=14},
		["é"] = {width=10,x=38,y=162,w=10,h=14,ox=0,oy=14},
		["ê"] = {width=10,x=49,y=162,w=10,h=14,ox=0,oy=14},
		["ë"] = {width=10,x=60,y=162,w=10,h=14,ox=0,oy=14},
		["ì"] = {width=5,x=71,y=162,w=5,h=14,ox=0,oy=14},
		["í"] = {width=5,x=77,y=162,w=5,h=14,ox=1,oy=14},
		["î"] = {width=5,x=83,y=162,w=6,h=14,ox=0,oy=14},
		["ï"] = {width=5,x=90,y=162,w=6,h=14,ox=0,oy=14},
		["ð"] = {width=11,x=97,y=162,w=10,h=14,ox=0,oy=14},
		["ñ"] = {width=11,x=108,y=162,w=9,h=14,ox=1,oy=14},
		["ò"] = {width=11,x=118,y=162,w=10,h=14,ox=0,oy=14},
		["ó"] = {width=11,x=129,y=162,w=10,h=14,ox=0,oy=14},
		["ô"] = {width=11,x=140,y=162,w=10,h=14,ox=0,oy=14},
		["õ"] = {width=11,x=151,y=162,w=10,h=14,ox=0,oy=14},
		["ö"] = {width=11,x=162,y=162,w=10,h=14,ox=0,oy=14},
		["÷"] = {width=11,x=173,y=164,w=11,h=10,ox=0,oy=12},
		["ø"] = {width=11,x=185,y=165,w=11,h=12,ox=0,oy=11},
		["ù"] = {width=11,x=197,y=162,w=9,h=14,ox=1,oy=14},
		["ú"] = {width=11,x=207,y=162,w=9,h=14,ox=1,oy=14},
		["û"] = {width=11,x=1,y=184,w=9,h=14,ox=1,oy=14},
		["ü"] = {width=11,x=11,y=184,w=9,h=14,ox=1,oy=14},
		["ý"] = {width=10,x=21,y=184,w=10,h=17,ox=0,oy=14},
		["þ"] = {width=10,x=32,y=184,w=9,h=17,ox=1,oy=14},
		["ÿ"] = {width=10,x=42,y=184,w=10,h=17,ox=0,oy=14},
		["Ą"] = {width=13,x=53,y=184,w=14,h=17,ox=0,oy=14},
		["ą"] = {width=10,x=68,y=188,w=10,h=13,ox=0,oy=10},
		["Ć"] = {width=13,x=79,y=180,w=13,h=18,ox=0,oy=18},
		["ć"] = {width=9,x=93,y=184,w=9,h=14,ox=0,oy=14},
		["Ę"] = {width=11,x=103,y=184,w=10,h=17,ox=1,oy=14},
		["ę"] = {width=10,x=114,y=188,w=10,h=13,ox=0,oy=10},
		["ı"] = {width=5,x=125,y=188,w=3,h=10,ox=1,oy=10},
		["Ł"] = {width=10,x=129,y=184,w=10,h=14,ox=0,oy=14},
		["ł"] = {width=6,x=140,y=184,w=6,h=14,ox=0,oy=14},
		["Ń"] = {width=14,x=147,y=180,w=12,h=18,ox=1,oy=18},
		["ń"] = {width=11,x=160,y=184,w=9,h=14,ox=1,oy=14},
		["Œ"] = {width=21,x=170,y=184,w=20,h=14,ox=0,oy=14},
		["œ"] = {width=16,x=191,y=188,w=16,h=10,ox=0,oy=10},
		["Ś"] = {width=10,x=208,y=180,w=10,h=18,ox=0,oy=18},
		["ś"] = {width=8,x=1,y=206,w=8,h=14,ox=0,oy=14},
		["Š"] = {width=10,x=10,y=203,w=10,h=17,ox=0,oy=17},
		["š"] = {width=8,x=21,y=206,w=8,h=14,ox=0,oy=14},
		["Ÿ"] = {width=12,x=30,y=202,w=12,h=18,ox=0,oy=18},
		["Ź"] = {width=12,x=43,y=202,w=12,h=18,ox=0,oy=18},
		["ź"] = {width=9,x=56,y=206,w=9,h=14,ox=0,oy=14},
		["Ż"] = {width=12,x=66,y=202,w=12,h=18,ox=0,oy=18},
		["ż"] = {width=9,x=79,y=206,w=9,h=14,ox=0,oy=14},
		["Ž"] = {width=12,x=89,y=203,w=12,h=17,ox=0,oy=17},
		["ž"] = {width=9,x=102,y=206,w=9,h=14,ox=0,oy=14},
		["ƒ"] = {width=11,x=112,y=206,w=9,h=17,ox=1,oy=14},
	},
	kernings={
		{from='"',to="&",offset=-1},
		{from='"',to=",",offset=-2},
		{from='"',to="-",offset=-1},
		{from='"',to=".",offset=-2},
		{from='"',to="/",offset=-1},
		{from='"',to="A",offset=-1},
		{from='"',to="c",offset=-1},
		{from='"',to="d",offset=-1},
		{from='"',to="e",offset=-1},
		{from='"',to="o",offset=-1},
		{from='"',to="q",offset=-1},
		{from='"',to="«",offset=-1},
		{from='"',to="­",offset=-1},
		{from='"',to="·",offset=-1},
		{from='"',to="»",offset=-1},
		{from='"',to="À",offset=-1},
		{from='"',to="Á",offset=-1},
		{from='"',to="Â",offset=-1},
		{from='"',to="Ã",offset=-1},
		{from='"',to="Ä",offset=-1},
		{from='"',to="Å",offset=-1},
		{from='"',to="Æ",offset=-1},
		{from='"',to="ç",offset=-1},
		{from='"',to="è",offset=-1},
		{from='"',to="é",offset=-1},
		{from='"',to="ê",offset=-1},
		{from='"',to="ë",offset=-1},
		{from='"',to="ð",offset=-1},
		{from='"',to="ò",offset=-1},
		{from='"',to="ó",offset=-1},
		{from='"',to="ô",offset=-1},
		{from='"',to="õ",offset=-1},
		{from='"',to="ö",offset=-1},
		{from='"',to="ø",offset=-1},
		{from='"',to="Ą",offset=-1},
		{from='"',to="ć",offset=-1},
		{from='"',to="ę",offset=-1},
		{from='"',to="œ",offset=-1},
		{from="'",to="&",offset=-1},
		{from="'",to=",",offset=-2},
		{from="'",to="-",offset=-1},
		{from="'",to=".",offset=-2},
		{from="'",to="/",offset=-1},
		{from="'",to="A",offset=-1},
		{from="'",to="c",offset=-1},
		{from="'",to="d",offset=-1},
		{from="'",to="e",offset=-1},
		{from="'",to="o",offset=-1},
		{from="'",to="q",offset=-1},
		{from="'",to="«",offset=-1},
		{from="'",to="­",offset=-1},
		{from="'",to="·",offset=-1},
		{from="'",to="»",offset=-1},
		{from="'",to="À",offset=-1},
		{from="'",to="Á",offset=-1},
		{from="'",to="Â",offset=-1},
		{from="'",to="Ã",offset=-1},
		{from="'",to="Ä",offset=-1},
		{from="'",to="Å",offset=-1},
		{from="'",to="Æ",offset=-1},
		{from="'",to="ç",offset=-1},
		{from="'",to="è",offset=-1},
		{from="'",to="é",offset=-1},
		{from="'",to="ê",offset=-1},
		{from="'",to="ë",offset=-1},
		{from="'",to="ð",offset=-1},
		{from="'",to="ò",offset=-1},
		{from="'",to="ó",offset=-1},
		{from="'",to="ô",offset=-1},
		{from="'",to="õ",offset=-1},
		{from="'",to="ö",offset=-1},
		{from="'",to="ø",offset=-1},
		{from="'",to="Ą",offset=-1},
		{from="'",to="ć",offset=-1},
		{from="'",to="ę",offset=-1},
		{from="'",to="œ",offset=-1},
		{from="*",to="&",offset=-1},
		{from="*",to=",",offset=-2},
		{from="*",to="-",offset=-1},
		{from="*",to=".",offset=-2},
		{from="*",to="/",offset=-1},
		{from="*",to="A",offset=-1},
		{from="*",to="c",offset=-1},
		{from="*",to="d",offset=-1},
		{from="*",to="e",offset=-1},
		{from="*",to="o",offset=-1},
		{from="*",to="q",offset=-1},
		{from="*",to="«",offset=-1},
		{from="*",to="­",offset=-1},
		{from="*",to="·",offset=-1},
		{from="*",to="»",offset=-1},
		{from="*",to="À",offset=-1},
		{from="*",to="Á",offset=-1},
		{from="*",to="Â",offset=-1},
		{from="*",to="Ã",offset=-1},
		{from="*",to="Ä",offset=-1},
		{from="*",to="Å",offset=-1},
		{from="*",to="Æ",offset=-1},
		{from="*",to="ç",offset=-1},
		{from="*",to="è",offset=-1},
		{from="*",to="é",offset=-1},
		{from="*",to="ê",offset=-1},
		{from="*",to="ë",offset=-1},
		{from="*",to="ð",offset=-1},
		{from="*",to="ò",offset=-1},
		{from="*",to="ó",offset=-1},
		{from="*",to="ô",offset=-1},
		{from="*",to="õ",offset=-1},
		{from="*",to="ö",offset=-1},
		{from="*",to="ø",offset=-1},
		{from="*",to="Ą",offset=-1},
		{from="*",to="ć",offset=-1},
		{from="*",to="ę",offset=-1},
		{from="*",to="œ",offset=-1},
		{from=",",to='"',offset=-2},
		{from=",",to="'",offset=-2},
		{from=",",to="*",offset=-2},
		{from=",",to="-",offset=-1},
		{from=",",to="T",offset=-1},
		{from=",",to="V",offset=-1},
		{from=",",to="W",offset=-1},
		{from=",",to="Y",offset=-1},
		{from=",",to="\\",offset=-1},
		{from=",",to="v",offset=-1},
		{from=",",to="y",offset=-1},
		{from=",",to="ª",offset=-2},
		{from=",",to="«",offset=-1},
		{from=",",to="­",offset=-1},
		{from=",",to="°",offset=-2},
		{from=",",to="·",offset=-1},
		{from=",",to="º",offset=-2},
		{from=",",to="»",offset=-1},
		{from=",",to="Ý",offset=-1},
		{from=",",to="Ÿ",offset=-1},
		{from="-",to='"',offset=-1},
		{from="-",to="'",offset=-1},
		{from="-",to="*",offset=-1},
		{from="-",to=",",offset=-1},
		{from="-",to=".",offset=-1},
		{from="-",to="T",offset=-1},
		{from="-",to="V",offset=-1},
		{from="-",to="Y",offset=-1},
		{from="-",to="\\",offset=-1},
		{from="-",to="ª",offset=-1},
		{from="-",to="°",offset=-1},
		{from="-",to="º",offset=-1},
		{from="-",to="Ý",offset=-1},
		{from="-",to="Ÿ",offset=-1},
		{from=".",to='"',offset=-2},
		{from=".",to="'",offset=-2},
		{from=".",to="*",offset=-2},
		{from=".",to="-",offset=-1},
		{from=".",to="T",offset=-1},
		{from=".",to="V",offset=-1},
		{from=".",to="W",offset=-1},
		{from=".",to="Y",offset=-1},
		{from=".",to="\\",offset=-1},
		{from=".",to="v",offset=-1},
		{from=".",to="y",offset=-1},
		{from=".",to="ª",offset=-2},
		{from=".",to="«",offset=-1},
		{from=".",to="­",offset=-1},
		{from=".",to="°",offset=-2},
		{from=".",to="·",offset=-1},
		{from=".",to="º",offset=-2},
		{from=".",to="»",offset=-1},
		{from=".",to="Ý",offset=-1},
		{from=".",to="Ÿ",offset=-1},
		{from="/",to="&",offset=-1},
		{from="/",to=",",offset=-1},
		{from="/",to="-",offset=-1},
		{from="/",to=".",offset=-1},
		{from="/",to=":",offset=-1},
		{from="/",to=";",offset=-1},
		{from="/",to="A",offset=-1},
		{from="/",to="J",offset=-1},
		{from="/",to="a",offset=-1},
		{from="/",to="c",offset=-1},
		{from="/",to="d",offset=-1},
		{from="/",to="e",offset=-1},
		{from="/",to="g",offset=-1},
		{from="/",to="m",offset=-1},
		{from="/",to="n",offset=-1},
		{from="/",to="o",offset=-1},
		{from="/",to="p",offset=-1},
		{from="/",to="q",offset=-1},
		{from="/",to="r",offset=-1},
		{from="/",to="s",offset=-1},
		{from="/",to="u",offset=-1},
		{from="/",to="z",offset=-1},
		{from="/",to="«",offset=-1},
		{from="/",to="­",offset=-1},
		{from="/",to="µ",offset=-1},
		{from="/",to="·",offset=-1},
		{from="/",to="»",offset=-1},
		{from="/",to="À",offset=-1},
		{from="/",to="Á",offset=-1},
		{from="/",to="Â",offset=-1},
		{from="/",to="Ã",offset=-1},
		{from="/",to="Ä",offset=-1},
		{from="/",to="Å",offset=-1},
		{from="/",to="Æ",offset=-1},
		{from="/",to="à",offset=-1},
		{from="/",to="á",offset=-1},
		{from="/",to="â",offset=-1},
		{from="/",to="ã",offset=-1},
		{from="/",to="ä",offset=-1},
		{from="/",to="å",offset=-1},
		{from="/",to="æ",offset=-1},
		{from="/",to="ç",offset=-1},
		{from="/",to="è",offset=-1},
		{from="/",to="é",offset=-1},
		{from="/",to="ê",offset=-1},
		{from="/",to="ë",offset=-1},
		{from="/",to="ð",offset=-1},
		{from="/",to="ñ",offset=-1},
		{from="/",to="ò",offset=-1},
		{from="/",to="ó",offset=-1},
		{from="/",to="ô",offset=-1},
		{from="/",to="õ",offset=-1},
		{from="/",to="ö",offset=-1},
		{from="/",to="ø",offset=-1},
		{from="/",to="ù",offset=-1},
		{from="/",to="ú",offset=-1},
		{from="/",to="û",offset=-1},
		{from="/",to="ü",offset=-1},
		{from="/",to="Ą",offset=-1},
		{from="/",to="ą",offset=-1},
		{from="/",to="ć",offset=-1},
		{from="/",to="ę",offset=-1},
		{from="/",to="ń",offset=-1},
		{from="/",to="œ",offset=-1},
		{from="@",to="T",offset=-1},
		{from="@",to="Y",offset=-1},
		{from="@",to="Ý",offset=-1},
		{from="@",to="Ÿ",offset=-1},
		{from="A",to='"',offset=-1},
		{from="A",to="'",offset=-1},
		{from="A",to="*",offset=-1},
		{from="A",to="T",offset=-1},
		{from="A",to="V",offset=-1},
		{from="A",to="W",offset=-1},
		{from="A",to="Y",offset=-1},
		{from="A",to="\\",offset=-1},
		{from="A",to="v",offset=-1},
		{from="A",to="y",offset=-1},
		{from="A",to="ª",offset=-1},
		{from="A",to="°",offset=-1},
		{from="A",to="²",offset=-1},
		{from="A",to="³",offset=-1},
		{from="A",to="¹",offset=-1},
		{from="A",to="º",offset=-1},
		{from="A",to="Ý",offset=-1},
		{from="A",to="Ÿ",offset=-1},
		{from="C",to="-",offset=-1},
		{from="C",to="«",offset=-1},
		{from="C",to="­",offset=-1},
		{from="C",to="·",offset=-1},
		{from="C",to="»",offset=-1},
		{from="D",to="T",offset=-1},
		{from="D",to="Y",offset=-1},
		{from="D",to="Ý",offset=-1},
		{from="D",to="Ÿ",offset=-1},
		{from="F",to="&",offset=-1},
		{from="F",to=",",offset=-1},
		{from="F",to=".",offset=-1},
		{from="F",to="/",offset=-1},
		{from="F",to="A",offset=-1},
		{from="F",to="J",offset=-1},
		{from="F",to="À",offset=-1},
		{from="F",to="Á",offset=-1},
		{from="F",to="Â",offset=-1},
		{from="F",to="Ã",offset=-1},
		{from="F",to="Ä",offset=-1},
		{from="F",to="Å",offset=-1},
		{from="F",to="Æ",offset=-1},
		{from="F",to="Ą",offset=-1},
		{from="K",to="t",offset=-1},
		{from="L",to='"',offset=-2},
		{from="L",to="'",offset=-2},
		{from="L",to="*",offset=-2},
		{from="L",to="-",offset=-1},
		{from="L",to="@",offset=-1},
		{from="L",to="C",offset=-1},
		{from="L",to="G",offset=-1},
		{from="L",to="O",offset=-1},
		{from="L",to="Q",offset=-1},
		{from="L",to="T",offset=-1},
		{from="L",to="V",offset=-1},
		{from="L",to="W",offset=-1},
		{from="L",to="Y",offset=-2},
		{from="L",to="\\",offset=-1},
		{from="L",to="v",offset=-1},
		{from="L",to="w",offset=-1},
		{from="L",to="y",offset=-1},
		{from="L",to="ª",offset=-2},
		{from="L",to="«",offset=-1},
		{from="L",to="­",offset=-1},
		{from="L",to="°",offset=-2},
		{from="L",to="²",offset=-1},
		{from="L",to="³",offset=-1},
		{from="L",to="·",offset=-1},
		{from="L",to="¹",offset=-1},
		{from="L",to="º",offset=-2},
		{from="L",to="»",offset=-1},
		{from="L",to="Ç",offset=-1},
		{from="L",to="Ò",offset=-1},
		{from="L",to="Ó",offset=-1},
		{from="L",to="Ô",offset=-1},
		{from="L",to="Õ",offset=-1},
		{from="L",to="Ö",offset=-1},
		{from="L",to="Ø",offset=-1},
		{from="L",to="Ý",offset=-2},
		{from="L",to="Ć",offset=-1},
		{from="L",to="Œ",offset=-1},
		{from="L",to="Ÿ",offset=-2},
		{from="O",to="T",offset=-1},
		{from="O",to="Y",offset=-1},
		{from="O",to="Ý",offset=-1},
		{from="O",to="Ÿ",offset=-1},
		{from="P",to="&",offset=-1},
		{from="P",to=",",offset=-2},
		{from="P",to=".",offset=-2},
		{from="P",to="/",offset=-1},
		{from="P",to="A",offset=-1},
		{from="P",to="J",offset=-1},
		{from="P",to="À",offset=-1},
		{from="P",to="Á",offset=-1},
		{from="P",to="Â",offset=-1},
		{from="P",to="Ã",offset=-1},
		{from="P",to="Ä",offset=-1},
		{from="P",to="Å",offset=-1},
		{from="P",to="Æ",offset=-1},
		{from="P",to="Ą",offset=-1},
		{from="Q",to="T",offset=-1},
		{from="Q",to="Y",offset=-1},
		{from="Q",to="Ý",offset=-1},
		{from="Q",to="Ÿ",offset=-1},
		{from="T",to="&",offset=-1},
		{from="T",to=",",offset=-1},
		{from="T",to="-",offset=-1},
		{from="T",to=".",offset=-1},
		{from="T",to="/",offset=-1},
		{from="T",to=":",offset=-1},
		{from="T",to=";",offset=-1},
		{from="T",to="@",offset=-1},
		{from="T",to="A",offset=-1},
		{from="T",to="C",offset=-1},
		{from="T",to="G",offset=-1},
		{from="T",to="J",offset=-1},
		{from="T",to="O",offset=-1},
		{from="T",to="Q",offset=-1},
		{from="T",to="a",offset=-2},
		{from="T",to="c",offset=-1},
		{from="T",to="d",offset=-1},
		{from="T",to="e",offset=-1},
		{from="T",to="g",offset=-1},
		{from="T",to="m",offset=-1},
		{from="T",to="n",offset=-1},
		{from="T",to="o",offset=-1},
		{from="T",to="p",offset=-1},
		{from="T",to="q",offset=-1},
		{from="T",to="r",offset=-1},
		{from="T",to="s",offset=-1},
		{from="T",to="u",offset=-1},
		{from="T",to="v",offset=-1},
		{from="T",to="w",offset=-1},
		{from="T",to="x",offset=-1},
		{from="T",to="y",offset=-1},
		{from="T",to="z",offset=-1},
		{from="T",to="«",offset=-1},
		{from="T",to="­",offset=-1},
		{from="T",to="µ",offset=-1},
		{from="T",to="·",offset=-1},
		{from="T",to="»",offset=-1},
		{from="T",to="À",offset=-1},
		{from="T",to="Á",offset=-1},
		{from="T",to="Â",offset=-1},
		{from="T",to="Ã",offset=-1},
		{from="T",to="Ä",offset=-1},
		{from="T",to="Å",offset=-1},
		{from="T",to="Æ",offset=-1},
		{from="T",to="Ç",offset=-1},
		{from="T",to="Ò",offset=-1},
		{from="T",to="Ó",offset=-1},
		{from="T",to="Ô",offset=-1},
		{from="T",to="Õ",offset=-1},
		{from="T",to="Ö",offset=-1},
		{from="T",to="Ø",offset=-1},
		{from="T",to="à",offset=-2},
		{from="T",to="á",offset=-2},
		{from="T",to="â",offset=-2},
		{from="T",to="ã",offset=-2},
		{from="T",to="ä",offset=-2},
		{from="T",to="å",offset=-2},
		{from="T",to="æ",offset=-2},
		{from="T",to="ç",offset=-1},
		{from="T",to="è",offset=-1},
		{from="T",to="é",offset=-1},
		{from="T",to="ê",offset=-1},
		{from="T",to="ë",offset=-1},
		{from="T",to="ð",offset=-1},
		{from="T",to="ñ",offset=-1},
		{from="T",to="ò",offset=-1},
		{from="T",to="ó",offset=-1},
		{from="T",to="ô",offset=-1},
		{from="T",to="õ",offset=-1},
		{from="T",to="ö",offset=-1},
		{from="T",to="ø",offset=-1},
		{from="T",to="ù",offset=-1},
		{from="T",to="ú",offset=-1},
		{from="T",to="û",offset=-1},
		{from="T",to="ü",offset=-1},
		{from="T",to="Ą",offset=-1},
		{from="T",to="ą",offset=-2},
		{from="T",to="Ć",offset=-1},
		{from="T",to="ć",offset=-1},
		{from="T",to="ę",offset=-1},
		{from="T",to="ń",offset=-1},
		{from="T",to="Œ",offset=-1},
		{from="T",to="œ",offset=-1},
		{from="V",to="&",offset=-1},
		{from="V",to=",",offset=-1},
		{from="V",to="-",offset=-1},
		{from="V",to=".",offset=-1},
		{from="V",to="/",offset=-1},
		{from="V",to=":",offset=-1},
		{from="V",to=";",offset=-1},
		{from="V",to="A",offset=-1},
		{from="V",to="J",offset=-1},
		{from="V",to="a",offset=-1},
		{from="V",to="c",offset=-1},
		{from="V",to="d",offset=-1},
		{from="V",to="e",offset=-1},
		{from="V",to="g",offset=-1},
		{from="V",to="m",offset=-1},
		{from="V",to="n",offset=-1},
		{from="V",to="o",offset=-1},
		{from="V",to="p",offset=-1},
		{from="V",to="q",offset=-1},
		{from="V",to="r",offset=-1},
		{from="V",to="s",offset=-1},
		{from="V",to="u",offset=-1},
		{from="V",to="z",offset=-1},
		{from="V",to="«",offset=-1},
		{from="V",to="­",offset=-1},
		{from="V",to="µ",offset=-1},
		{from="V",to="·",offset=-1},
		{from="V",to="»",offset=-1},
		{from="V",to="À",offset=-1},
		{from="V",to="Á",offset=-1},
		{from="V",to="Â",offset=-1},
		{from="V",to="Ã",offset=-1},
		{from="V",to="Ä",offset=-1},
		{from="V",to="Å",offset=-1},
		{from="V",to="Æ",offset=-1},
		{from="V",to="à",offset=-1},
		{from="V",to="á",offset=-1},
		{from="V",to="â",offset=-1},
		{from="V",to="ã",offset=-1},
		{from="V",to="ä",offset=-1},
		{from="V",to="å",offset=-1},
		{from="V",to="æ",offset=-1},
		{from="V",to="ç",offset=-1},
		{from="V",to="è",offset=-1},
		{from="V",to="é",offset=-1},
		{from="V",to="ê",offset=-1},
		{from="V",to="ë",offset=-1},
		{from="V",to="ð",offset=-1},
		{from="V",to="ñ",offset=-1},
		{from="V",to="ò",offset=-1},
		{from="V",to="ó",offset=-1},
		{from="V",to="ô",offset=-1},
		{from="V",to="õ",offset=-1},
		{from="V",to="ö",offset=-1},
		{from="V",to="ø",offset=-1},
		{from="V",to="ù",offset=-1},
		{from="V",to="ú",offset=-1},
		{from="V",to="û",offset=-1},
		{from="V",to="ü",offset=-1},
		{from="V",to="Ą",offset=-1},
		{from="V",to="ą",offset=-1},
		{from="V",to="ć",offset=-1},
		{from="V",to="ę",offset=-1},
		{from="V",to="ń",offset=-1},
		{from="V",to="œ",offset=-1},
		{from="W",to="&",offset=-1},
		{from="W",to=",",offset=-1},
		{from="W",to=".",offset=-1},
		{from="W",to="/",offset=-1},
		{from="W",to="A",offset=-1},
		{from="W",to="J",offset=-1},
		{from="W",to="a",offset=-1},
		{from="W",to="g",offset=-1},
		{from="W",to="À",offset=-1},
		{from="W",to="Á",offset=-1},
		{from="W",to="Â",offset=-1},
		{from="W",to="Ã",offset=-1},
		{from="W",to="Ä",offset=-1},
		{from="W",to="Å",offset=-1},
		{from="W",to="Æ",offset=-1},
		{from="W",to="à",offset=-1},
		{from="W",to="á",offset=-1},
		{from="W",to="â",offset=-1},
		{from="W",to="ã",offset=-1},
		{from="W",to="ä",offset=-1},
		{from="W",to="å",offset=-1},
		{from="W",to="æ",offset=-1},
		{from="W",to="Ą",offset=-1},
		{from="W",to="ą",offset=-1},
		{from="X",to="t",offset=-1},
		{from="Y",to="&",offset=-1},
		{from="Y",to=",",offset=-1},
		{from="Y",to="-",offset=-1},
		{from="Y",to=".",offset=-1},
		{from="Y",to="/",offset=-1},
		{from="Y",to=":",offset=-1},
		{from="Y",to=";",offset=-1},
		{from="Y",to="@",offset=-1},
		{from="Y",to="A",offset=-1},
		{from="Y",to="C",offset=-1},
		{from="Y",to="G",offset=-1},
		{from="Y",to="J",offset=-1},
		{from="Y",to="O",offset=-1},
		{from="Y",to="Q",offset=-1},
		{from="Y",to="a",offset=-1},
		{from="Y",to="c",offset=-1},
		{from="Y",to="d",offset=-1},
		{from="Y",to="e",offset=-1},
		{from="Y",to="g",offset=-1},
		{from="Y",to="m",offset=-1},
		{from="Y",to="n",offset=-1},
		{from="Y",to="o",offset=-1},
		{from="Y",to="p",offset=-1},
		{from="Y",to="q",offset=-1},
		{from="Y",to="r",offset=-1},
		{from="Y",to="s",offset=-1},
		{from="Y",to="u",offset=-1},
		{from="Y",to="v",offset=-1},
		{from="Y",to="w",offset=-1},
		{from="Y",to="x",offset=-1},
		{from="Y",to="y",offset=-1},
		{from="Y",to="«",offset=-1},
		{from="Y",to="­",offset=-1},
		{from="Y",to="µ",offset=-1},
		{from="Y",to="·",offset=-1},
		{from="Y",to="»",offset=-1},
		{from="Y",to="À",offset=-1},
		{from="Y",to="Á",offset=-1},
		{from="Y",to="Â",offset=-1},
		{from="Y",to="Ã",offset=-1},
		{from="Y",to="Ä",offset=-1},
		{from="Y",to="Å",offset=-1},
		{from="Y",to="Æ",offset=-1},
		{from="Y",to="Ç",offset=-1},
		{from="Y",to="Ò",offset=-1},
		{from="Y",to="Ó",offset=-1},
		{from="Y",to="Ô",offset=-1},
		{from="Y",to="Õ",offset=-1},
		{from="Y",to="Ö",offset=-1},
		{from="Y",to="Ø",offset=-1},
		{from="Y",to="à",offset=-1},
		{from="Y",to="á",offset=-1},
		{from="Y",to="â",offset=-1},
		{from="Y",to="ã",offset=-1},
		{from="Y",to="ä",offset=-1},
		{from="Y",to="å",offset=-1},
		{from="Y",to="æ",offset=-1},
		{from="Y",to="ç",offset=-1},
		{from="Y",to="è",offset=-1},
		{from="Y",to="é",offset=-1},
		{from="Y",to="ê",offset=-1},
		{from="Y",to="ë",offset=-1},
		{from="Y",to="ð",offset=-1},
		{from="Y",to="ñ",offset=-1},
		{from="Y",to="ò",offset=-1},
		{from="Y",to="ó",offset=-1},
		{from="Y",to="ô",offset=-1},
		{from="Y",to="õ",offset=-1},
		{from="Y",to="ö",offset=-1},
		{from="Y",to="ø",offset=-1},
		{from="Y",to="ù",offset=-1},
		{from="Y",to="ú",offset=-1},
		{from="Y",to="û",offset=-1},
		{from="Y",to="ü",offset=-1},
		{from="Y",to="Ą",offset=-1},
		{from="Y",to="ą",offset=-1},
		{from="Y",to="Ć",offset=-1},
		{from="Y",to="ć",offset=-1},
		{from="Y",to="ę",offset=-1},
		{from="Y",to="ń",offset=-1},
		{from="Y",to="Œ",offset=-1},
		{from="Y",to="œ",offset=-1},
		{from="\\",to='"',offset=-1},
		{from="\\",to="'",offset=-1},
		{from="\\",to="*",offset=-1},
		{from="\\",to="T",offset=-1},
		{from="\\",to="V",offset=-1},
		{from="\\",to="W",offset=-1},
		{from="\\",to="Y",offset=-1},
		{from="\\",to="v",offset=-1},
		{from="\\",to="y",offset=-1},
		{from="\\",to="ª",offset=-1},
		{from="\\",to="°",offset=-1},
		{from="\\",to="²",offset=-1},
		{from="\\",to="³",offset=-1},
		{from="\\",to="¹",offset=-1},
		{from="\\",to="º",offset=-1},
		{from="\\",to="Ý",offset=-1},
		{from="\\",to="Ÿ",offset=-1},
		{from="a",to='"',offset=-1},
		{from="a",to="'",offset=-1},
		{from="a",to="*",offset=-1},
		{from="a",to="ª",offset=-1},
		{from="a",to="°",offset=-1},
		{from="a",to="²",offset=-1},
		{from="a",to="³",offset=-1},
		{from="a",to="¹",offset=-1},
		{from="a",to="º",offset=-1},
		{from="b",to='"',offset=-1},
		{from="b",to="'",offset=-1},
		{from="b",to="*",offset=-1},
		{from="b",to="V",offset=-1},
		{from="b",to="\\",offset=-1},
		{from="b",to="ª",offset=-1},
		{from="b",to="°",offset=-1},
		{from="b",to="º",offset=-1},
		{from="e",to='"',offset=-1},
		{from="e",to="'",offset=-1},
		{from="e",to="*",offset=-1},
		{from="e",to="V",offset=-1},
		{from="e",to="\\",offset=-1},
		{from="e",to="ª",offset=-1},
		{from="e",to="°",offset=-1},
		{from="e",to="º",offset=-1},
		{from="f",to=",",offset=-1},
		{from="f",to=".",offset=-1},
		{from="f",to="²",offset=1},
		{from="f",to="³",offset=1},
		{from="f",to="¹",offset=1},
		{from="h",to='"',offset=-1},
		{from="h",to="'",offset=-1},
		{from="h",to="*",offset=-1},
		{from="h",to="ª",offset=-1},
		{from="h",to="°",offset=-1},
		{from="h",to="²",offset=-1},
		{from="h",to="³",offset=-1},
		{from="h",to="¹",offset=-1},
		{from="h",to="º",offset=-1},
		{from="m",to='"',offset=-1},
		{from="m",to="'",offset=-1},
		{from="m",to="*",offset=-1},
		{from="m",to="ª",offset=-1},
		{from="m",to="°",offset=-1},
		{from="m",to="²",offset=-1},
		{from="m",to="³",offset=-1},
		{from="m",to="¹",offset=-1},
		{from="m",to="º",offset=-1},
		{from="n",to='"',offset=-1},
		{from="n",to="'",offset=-1},
		{from="n",to="*",offset=-1},
		{from="n",to="ª",offset=-1},
		{from="n",to="°",offset=-1},
		{from="n",to="²",offset=-1},
		{from="n",to="³",offset=-1},
		{from="n",to="¹",offset=-1},
		{from="n",to="º",offset=-1},
		{from="o",to='"',offset=-1},
		{from="o",to="'",offset=-1},
		{from="o",to="*",offset=-1},
		{from="o",to="V",offset=-1},
		{from="o",to="\\",offset=-1},
		{from="o",to="ª",offset=-1},
		{from="o",to="°",offset=-1},
		{from="o",to="º",offset=-1},
		{from="p",to='"',offset=-1},
		{from="p",to="'",offset=-1},
		{from="p",to="*",offset=-1},
		{from="p",to="V",offset=-1},
		{from="p",to="\\",offset=-1},
		{from="p",to="ª",offset=-1},
		{from="p",to="°",offset=-1},
		{from="p",to="º",offset=-1},
		{from="r",to=",",offset=-1},
		{from="r",to=".",offset=-1},
		{from="v",to="&",offset=-1},
		{from="v",to=",",offset=-1},
		{from="v",to=".",offset=-1},
		{from="v",to="/",offset=-1},
		{from="v",to="A",offset=-1},
		{from="v",to="À",offset=-1},
		{from="v",to="Á",offset=-1},
		{from="v",to="Â",offset=-1},
		{from="v",to="Ã",offset=-1},
		{from="v",to="Ä",offset=-1},
		{from="v",to="Å",offset=-1},
		{from="v",to="Æ",offset=-1},
		{from="v",to="Ą",offset=-1},
		{from="y",to="&",offset=-1},
		{from="y",to=",",offset=-1},
		{from="y",to=".",offset=-1},
		{from="y",to="/",offset=-1},
		{from="y",to="A",offset=-1},
		{from="y",to="À",offset=-1},
		{from="y",to="Á",offset=-1},
		{from="y",to="Â",offset=-1},
		{from="y",to="Ã",offset=-1},
		{from="y",to="Ä",offset=-1},
		{from="y",to="Å",offset=-1},
		{from="y",to="Æ",offset=-1},
		{from="y",to="Ą",offset=-1},
		{from="ª",to="&",offset=-1},
		{from="ª",to=",",offset=-2},
		{from="ª",to="-",offset=-1},
		{from="ª",to=".",offset=-2},
		{from="ª",to="/",offset=-1},
		{from="ª",to="A",offset=-1},
		{from="ª",to="c",offset=-1},
		{from="ª",to="d",offset=-1},
		{from="ª",to="e",offset=-1},
		{from="ª",to="o",offset=-1},
		{from="ª",to="q",offset=-1},
		{from="ª",to="«",offset=-1},
		{from="ª",to="­",offset=-1},
		{from="ª",to="·",offset=-1},
		{from="ª",to="»",offset=-1},
		{from="ª",to="À",offset=-1},
		{from="ª",to="Á",offset=-1},
		{from="ª",to="Â",offset=-1},
		{from="ª",to="Ã",offset=-1},
		{from="ª",to="Ä",offset=-1},
		{from="ª",to="Å",offset=-1},
		{from="ª",to="Æ",offset=-1},
		{from="ª",to="ç",offset=-1},
		{from="ª",to="è",offset=-1},
		{from="ª",to="é",offset=-1},
		{from="ª",to="ê",offset=-1},
		{from="ª",to="ë",offset=-1},
		{from="ª",to="ð",offset=-1},
		{from="ª",to="ò",offset=-1},
		{from="ª",to="ó",offset=-1},
		{from="ª",to="ô",offset=-1},
		{from="ª",to="õ",offset=-1},
		{from="ª",to="ö",offset=-1},
		{from="ª",to="ø",offset=-1},
		{from="ª",to="Ą",offset=-1},
		{from="ª",to="ć",offset=-1},
		{from="ª",to="ę",offset=-1},
		{from="ª",to="œ",offset=-1},
		{from="«",to='"',offset=-1},
		{from="«",to="'",offset=-1},
		{from="«",to="*",offset=-1},
		{from="«",to=",",offset=-1},
		{from="«",to=".",offset=-1},
		{from="«",to="T",offset=-1},
		{from="«",to="V",offset=-1},
		{from="«",to="Y",offset=-1},
		{from="«",to="\\",offset=-1},
		{from="«",to="ª",offset=-1},
		{from="«",to="°",offset=-1},
		{from="«",to="º",offset=-1},
		{from="«",to="Ý",offset=-1},
		{from="«",to="Ÿ",offset=-1},
		{from="­",to='"',offset=-1},
		{from="­",to="'",offset=-1},
		{from="­",to="*",offset=-1},
		{from="­",to=",",offset=-1},
		{from="­",to=".",offset=-1},
		{from="­",to="T",offset=-1},
		{from="­",to="V",offset=-1},
		{from="­",to="Y",offset=-1},
		{from="­",to="\\",offset=-1},
		{from="­",to="ª",offset=-1},
		{from="­",to="°",offset=-1},
		{from="­",to="º",offset=-1},
		{from="­",to="Ý",offset=-1},
		{from="­",to="Ÿ",offset=-1},
		{from="®",to="T",offset=-1},
		{from="®",to="Y",offset=-1},
		{from="®",to="Ý",offset=-1},
		{from="®",to="Ÿ",offset=-1},
		{from="°",to="&",offset=-1},
		{from="°",to=",",offset=-2},
		{from="°",to="-",offset=-1},
		{from="°",to=".",offset=-2},
		{from="°",to="/",offset=-1},
		{from="°",to="A",offset=-1},
		{from="°",to="c",offset=-1},
		{from="°",to="d",offset=-1},
		{from="°",to="e",offset=-1},
		{from="°",to="o",offset=-1},
		{from="°",to="q",offset=-1},
		{from="°",to="«",offset=-1},
		{from="°",to="­",offset=-1},
		{from="°",to="·",offset=-1},
		{from="°",to="»",offset=-1},
		{from="°",to="À",offset=-1},
		{from="°",to="Á",offset=-1},
		{from="°",to="Â",offset=-1},
		{from="°",to="Ã",offset=-1},
		{from="°",to="Ä",offset=-1},
		{from="°",to="Å",offset=-1},
		{from="°",to="Æ",offset=-1},
		{from="°",to="ç",offset=-1},
		{from="°",to="è",offset=-1},
		{from="°",to="é",offset=-1},
		{from="°",to="ê",offset=-1},
		{from="°",to="ë",offset=-1},
		{from="°",to="ð",offset=-1},
		{from="°",to="ò",offset=-1},
		{from="°",to="ó",offset=-1},
		{from="°",to="ô",offset=-1},
		{from="°",to="õ",offset=-1},
		{from="°",to="ö",offset=-1},
		{from="°",to="ø",offset=-1},
		{from="°",to="Ą",offset=-1},
		{from="°",to="ć",offset=-1},
		{from="°",to="ę",offset=-1},
		{from="°",to="œ",offset=-1},
		{from="²",to="&",offset=-1},
		{from="²",to="/",offset=-1},
		{from="²",to="A",offset=-1},
		{from="²",to="À",offset=-1},
		{from="²",to="Á",offset=-1},
		{from="²",to="Â",offset=-1},
		{from="²",to="Ã",offset=-1},
		{from="²",to="Ä",offset=-1},
		{from="²",to="Å",offset=-1},
		{from="²",to="Æ",offset=-1},
		{from="²",to="Ą",offset=-1},
		{from="³",to="&",offset=-1},
		{from="³",to="/",offset=-1},
		{from="³",to="A",offset=-1},
		{from="³",to="À",offset=-1},
		{from="³",to="Á",offset=-1},
		{from="³",to="Â",offset=-1},
		{from="³",to="Ã",offset=-1},
		{from="³",to="Ä",offset=-1},
		{from="³",to="Å",offset=-1},
		{from="³",to="Æ",offset=-1},
		{from="³",to="Ą",offset=-1},
		{from="·",to='"',offset=-1},
		{from="·",to="'",offset=-1},
		{from="·",to="*",offset=-1},
		{from="·",to=",",offset=-1},
		{from="·",to=".",offset=-1},
		{from="·",to="T",offset=-1},
		{from="·",to="V",offset=-1},
		{from="·",to="Y",offset=-1},
		{from="·",to="\\",offset=-1},
		{from="·",to="ª",offset=-1},
		{from="·",to="°",offset=-1},
		{from="·",to="º",offset=-1},
		{from="·",to="Ý",offset=-1},
		{from="·",to="Ÿ",offset=-1},
		{from="¹",to="&",offset=-1},
		{from="¹",to="/",offset=-1},
		{from="¹",to="A",offset=-1},
		{from="¹",to="À",offset=-1},
		{from="¹",to="Á",offset=-1},
		{from="¹",to="Â",offset=-1},
		{from="¹",to="Ã",offset=-1},
		{from="¹",to="Ä",offset=-1},
		{from="¹",to="Å",offset=-1},
		{from="¹",to="Æ",offset=-1},
		{from="¹",to="Ą",offset=-1},
		{from="º",to="&",offset=-1},
		{from="º",to=",",offset=-2},
		{from="º",to="-",offset=-1},
		{from="º",to=".",offset=-2},
		{from="º",to="/",offset=-1},
		{from="º",to="A",offset=-1},
		{from="º",to="c",offset=-1},
		{from="º",to="d",offset=-1},
		{from="º",to="e",offset=-1},
		{from="º",to="o",offset=-1},
		{from="º",to="q",offset=-1},
		{from="º",to="«",offset=-1},
		{from="º",to="­",offset=-1},
		{from="º",to="·",offset=-1},
		{from="º",to="»",offset=-1},
		{from="º",to="À",offset=-1},
		{from="º",to="Á",offset=-1},
		{from="º",to="Â",offset=-1},
		{from="º",to="Ã",offset=-1},
		{from="º",to="Ä",offset=-1},
		{from="º",to="Å",offset=-1},
		{from="º",to="Æ",offset=-1},
		{from="º",to="ç",offset=-1},
		{from="º",to="è",offset=-1},
		{from="º",to="é",offset=-1},
		{from="º",to="ê",offset=-1},
		{from="º",to="ë",offset=-1},
		{from="º",to="ð",offset=-1},
		{from="º",to="ò",offset=-1},
		{from="º",to="ó",offset=-1},
		{from="º",to="ô",offset=-1},
		{from="º",to="õ",offset=-1},
		{from="º",to="ö",offset=-1},
		{from="º",to="ø",offset=-1},
		{from="º",to="Ą",offset=-1},
		{from="º",to="ć",offset=-1},
		{from="º",to="ę",offset=-1},
		{from="º",to="œ",offset=-1},
		{from="»",to='"',offset=-1},
		{from="»",to="'",offset=-1},
		{from="»",to="*",offset=-1},
		{from="»",to=",",offset=-1},
		{from="»",to=".",offset=-1},
		{from="»",to="T",offset=-1},
		{from="»",to="V",offset=-1},
		{from="»",to="Y",offset=-1},
		{from="»",to="\\",offset=-1},
		{from="»",to="ª",offset=-1},
		{from="»",to="°",offset=-1},
		{from="»",to="º",offset=-1},
		{from="»",to="Ý",offset=-1},
		{from="»",to="Ÿ",offset=-1},
		{from="À",to='"',offset=-1},
		{from="À",to="'",offset=-1},
		{from="À",to="*",offset=-1},
		{from="À",to="T",offset=-1},
		{from="À",to="V",offset=-1},
		{from="À",to="W",offset=-1},
		{from="À",to="Y",offset=-1},
		{from="À",to="\\",offset=-1},
		{from="À",to="v",offset=-1},
		{from="À",to="y",offset=-1},
		{from="À",to="ª",offset=-1},
		{from="À",to="°",offset=-1},
		{from="À",to="²",offset=-1},
		{from="À",to="³",offset=-1},
		{from="À",to="¹",offset=-1},
		{from="À",to="º",offset=-1},
		{from="À",to="Ý",offset=-1},
		{from="À",to="Ÿ",offset=-1},
		{from="Á",to='"',offset=-1},
		{from="Á",to="'",offset=-1},
		{from="Á",to="*",offset=-1},
		{from="Á",to="T",offset=-1},
		{from="Á",to="V",offset=-1},
		{from="Á",to="W",offset=-1},
		{from="Á",to="Y",offset=-1},
		{from="Á",to="\\",offset=-1},
		{from="Á",to="v",offset=-1},
		{from="Á",to="y",offset=-1},
		{from="Á",to="ª",offset=-1},
		{from="Á",to="°",offset=-1},
		{from="Á",to="²",offset=-1},
		{from="Á",to="³",offset=-1},
		{from="Á",to="¹",offset=-1},
		{from="Á",to="º",offset=-1},
		{from="Á",to="Ý",offset=-1},
		{from="Á",to="Ÿ",offset=-1},
		{from="Â",to='"',offset=-1},
		{from="Â",to="'",offset=-1},
		{from="Â",to="*",offset=-1},
		{from="Â",to="T",offset=-1},
		{from="Â",to="V",offset=-1},
		{from="Â",to="W",offset=-1},
		{from="Â",to="Y",offset=-1},
		{from="Â",to="\\",offset=-1},
		{from="Â",to="v",offset=-1},
		{from="Â",to="y",offset=-1},
		{from="Â",to="ª",offset=-1},
		{from="Â",to="°",offset=-1},
		{from="Â",to="²",offset=-1},
		{from="Â",to="³",offset=-1},
		{from="Â",to="¹",offset=-1},
		{from="Â",to="º",offset=-1},
		{from="Â",to="Ý",offset=-1},
		{from="Â",to="Ÿ",offset=-1},
		{from="Ã",to='"',offset=-1},
		{from="Ã",to="'",offset=-1},
		{from="Ã",to="*",offset=-1},
		{from="Ã",to="T",offset=-1},
		{from="Ã",to="V",offset=-1},
		{from="Ã",to="W",offset=-1},
		{from="Ã",to="Y",offset=-1},
		{from="Ã",to="\\",offset=-1},
		{from="Ã",to="v",offset=-1},
		{from="Ã",to="y",offset=-1},
		{from="Ã",to="ª",offset=-1},
		{from="Ã",to="°",offset=-1},
		{from="Ã",to="²",offset=-1},
		{from="Ã",to="³",offset=-1},
		{from="Ã",to="¹",offset=-1},
		{from="Ã",to="º",offset=-1},
		{from="Ã",to="Ý",offset=-1},
		{from="Ã",to="Ÿ",offset=-1},
		{from="Ä",to='"',offset=-1},
		{from="Ä",to="'",offset=-1},
		{from="Ä",to="*",offset=-1},
		{from="Ä",to="T",offset=-1},
		{from="Ä",to="V",offset=-1},
		{from="Ä",to="W",offset=-1},
		{from="Ä",to="Y",offset=-1},
		{from="Ä",to="\\",offset=-1},
		{from="Ä",to="v",offset=-1},
		{from="Ä",to="y",offset=-1},
		{from="Ä",to="ª",offset=-1},
		{from="Ä",to="°",offset=-1},
		{from="Ä",to="²",offset=-1},
		{from="Ä",to="³",offset=-1},
		{from="Ä",to="¹",offset=-1},
		{from="Ä",to="º",offset=-1},
		{from="Ä",to="Ý",offset=-1},
		{from="Ä",to="Ÿ",offset=-1},
		{from="Å",to='"',offset=-1},
		{from="Å",to="'",offset=-1},
		{from="Å",to="*",offset=-1},
		{from="Å",to="T",offset=-1},
		{from="Å",to="V",offset=-1},
		{from="Å",to="W",offset=-1},
		{from="Å",to="Y",offset=-1},
		{from="Å",to="\\",offset=-1},
		{from="Å",to="v",offset=-1},
		{from="Å",to="y",offset=-1},
		{from="Å",to="ª",offset=-1},
		{from="Å",to="°",offset=-1},
		{from="Å",to="²",offset=-1},
		{from="Å",to="³",offset=-1},
		{from="Å",to="¹",offset=-1},
		{from="Å",to="º",offset=-1},
		{from="Å",to="Ý",offset=-1},
		{from="Å",to="Ÿ",offset=-1},
		{from="Ç",to="-",offset=-1},
		{from="Ç",to="«",offset=-1},
		{from="Ç",to="­",offset=-1},
		{from="Ç",to="·",offset=-1},
		{from="Ç",to="»",offset=-1},
		{from="Ð",to="T",offset=-1},
		{from="Ð",to="Y",offset=-1},
		{from="Ð",to="Ý",offset=-1},
		{from="Ð",to="Ÿ",offset=-1},
		{from="Ò",to="T",offset=-1},
		{from="Ò",to="Y",offset=-1},
		{from="Ò",to="Ý",offset=-1},
		{from="Ò",to="Ÿ",offset=-1},
		{from="Ó",to="T",offset=-1},
		{from="Ó",to="Y",offset=-1},
		{from="Ó",to="Ý",offset=-1},
		{from="Ó",to="Ÿ",offset=-1},
		{from="Ô",to="T",offset=-1},
		{from="Ô",to="Y",offset=-1},
		{from="Ô",to="Ý",offset=-1},
		{from="Ô",to="Ÿ",offset=-1},
		{from="Õ",to="T",offset=-1},
		{from="Õ",to="Y",offset=-1},
		{from="Õ",to="Ý",offset=-1},
		{from="Õ",to="Ÿ",offset=-1},
		{from="Ö",to="T",offset=-1},
		{from="Ö",to="Y",offset=-1},
		{from="Ö",to="Ý",offset=-1},
		{from="Ö",to="Ÿ",offset=-1},
		{from="Ý",to="&",offset=-1},
		{from="Ý",to=",",offset=-1},
		{from="Ý",to="-",offset=-1},
		{from="Ý",to=".",offset=-1},
		{from="Ý",to="/",offset=-1},
		{from="Ý",to=":",offset=-1},
		{from="Ý",to=";",offset=-1},
		{from="Ý",to="@",offset=-1},
		{from="Ý",to="A",offset=-1},
		{from="Ý",to="C",offset=-1},
		{from="Ý",to="G",offset=-1},
		{from="Ý",to="J",offset=-1},
		{from="Ý",to="O",offset=-1},
		{from="Ý",to="Q",offset=-1},
		{from="Ý",to="a",offset=-1},
		{from="Ý",to="c",offset=-1},
		{from="Ý",to="d",offset=-1},
		{from="Ý",to="e",offset=-1},
		{from="Ý",to="g",offset=-1},
		{from="Ý",to="m",offset=-1},
		{from="Ý",to="n",offset=-1},
		{from="Ý",to="o",offset=-1},
		{from="Ý",to="p",offset=-1},
		{from="Ý",to="q",offset=-1},
		{from="Ý",to="r",offset=-1},
		{from="Ý",to="s",offset=-1},
		{from="Ý",to="u",offset=-1},
		{from="Ý",to="v",offset=-1},
		{from="Ý",to="w",offset=-1},
		{from="Ý",to="x",offset=-1},
		{from="Ý",to="y",offset=-1},
		{from="Ý",to="«",offset=-1},
		{from="Ý",to="­",offset=-1},
		{from="Ý",to="µ",offset=-1},
		{from="Ý",to="·",offset=-1},
		{from="Ý",to="»",offset=-1},
		{from="Ý",to="À",offset=-1},
		{from="Ý",to="Á",offset=-1},
		{from="Ý",to="Â",offset=-1},
		{from="Ý",to="Ã",offset=-1},
		{from="Ý",to="Ä",offset=-1},
		{from="Ý",to="Å",offset=-1},
		{from="Ý",to="Æ",offset=-1},
		{from="Ý",to="Ç",offset=-1},
		{from="Ý",to="Ò",offset=-1},
		{from="Ý",to="Ó",offset=-1},
		{from="Ý",to="Ô",offset=-1},
		{from="Ý",to="Õ",offset=-1},
		{from="Ý",to="Ö",offset=-1},
		{from="Ý",to="Ø",offset=-1},
		{from="Ý",to="à",offset=-1},
		{from="Ý",to="á",offset=-1},
		{from="Ý",to="â",offset=-1},
		{from="Ý",to="ã",offset=-1},
		{from="Ý",to="ä",offset=-1},
		{from="Ý",to="å",offset=-1},
		{from="Ý",to="æ",offset=-1},
		{from="Ý",to="ç",offset=-1},
		{from="Ý",to="è",offset=-1},
		{from="Ý",to="é",offset=-1},
		{from="Ý",to="ê",offset=-1},
		{from="Ý",to="ë",offset=-1},
		{from="Ý",to="ð",offset=-1},
		{from="Ý",to="ñ",offset=-1},
		{from="Ý",to="ò",offset=-1},
		{from="Ý",to="ó",offset=-1},
		{from="Ý",to="ô",offset=-1},
		{from="Ý",to="õ",offset=-1},
		{from="Ý",to="ö",offset=-1},
		{from="Ý",to="ø",offset=-1},
		{from="Ý",to="ù",offset=-1},
		{from="Ý",to="ú",offset=-1},
		{from="Ý",to="û",offset=-1},
		{from="Ý",to="ü",offset=-1},
		{from="Ý",to="Ą",offset=-1},
		{from="Ý",to="ą",offset=-1},
		{from="Ý",to="Ć",offset=-1},
		{from="Ý",to="ć",offset=-1},
		{from="Ý",to="ę",offset=-1},
		{from="Ý",to="ń",offset=-1},
		{from="Ý",to="Œ",offset=-1},
		{from="Ý",to="œ",offset=-1},
		{from="Þ",to="T",offset=-1},
		{from="Þ",to="Y",offset=-1},
		{from="Þ",to="Ý",offset=-1},
		{from="Þ",to="Ÿ",offset=-1},
		{from="à",to='"',offset=-1},
		{from="à",to="'",offset=-1},
		{from="à",to="*",offset=-1},
		{from="à",to="ª",offset=-1},
		{from="à",to="°",offset=-1},
		{from="à",to="²",offset=-1},
		{from="à",to="³",offset=-1},
		{from="à",to="¹",offset=-1},
		{from="à",to="º",offset=-1},
		{from="á",to='"',offset=-1},
		{from="á",to="'",offset=-1},
		{from="á",to="*",offset=-1},
		{from="á",to="ª",offset=-1},
		{from="á",to="°",offset=-1},
		{from="á",to="²",offset=-1},
		{from="á",to="³",offset=-1},
		{from="á",to="¹",offset=-1},
		{from="á",to="º",offset=-1},
		{from="â",to='"',offset=-1},
		{from="â",to="'",offset=-1},
		{from="â",to="*",offset=-1},
		{from="â",to="ª",offset=-1},
		{from="â",to="°",offset=-1},
		{from="â",to="²",offset=-1},
		{from="â",to="³",offset=-1},
		{from="â",to="¹",offset=-1},
		{from="â",to="º",offset=-1},
		{from="ã",to='"',offset=-1},
		{from="ã",to="'",offset=-1},
		{from="ã",to="*",offset=-1},
		{from="ã",to="ª",offset=-1},
		{from="ã",to="°",offset=-1},
		{from="ã",to="²",offset=-1},
		{from="ã",to="³",offset=-1},
		{from="ã",to="¹",offset=-1},
		{from="ã",to="º",offset=-1},
		{from="ä",to='"',offset=-1},
		{from="ä",to="'",offset=-1},
		{from="ä",to="*",offset=-1},
		{from="ä",to="ª",offset=-1},
		{from="ä",to="°",offset=-1},
		{from="ä",to="²",offset=-1},
		{from="ä",to="³",offset=-1},
		{from="ä",to="¹",offset=-1},
		{from="ä",to="º",offset=-1},
		{from="å",to='"',offset=-1},
		{from="å",to="'",offset=-1},
		{from="å",to="*",offset=-1},
		{from="å",to="ª",offset=-1},
		{from="å",to="°",offset=-1},
		{from="å",to="²",offset=-1},
		{from="å",to="³",offset=-1},
		{from="å",to="¹",offset=-1},
		{from="å",to="º",offset=-1},
		{from="æ",to='"',offset=-1},
		{from="æ",to="'",offset=-1},
		{from="æ",to="*",offset=-1},
		{from="æ",to="V",offset=-1},
		{from="æ",to="\\",offset=-1},
		{from="æ",to="ª",offset=-1},
		{from="æ",to="°",offset=-1},
		{from="æ",to="º",offset=-1},
		{from="è",to='"',offset=-1},
		{from="è",to="'",offset=-1},
		{from="è",to="*",offset=-1},
		{from="è",to="V",offset=-1},
		{from="è",to="\\",offset=-1},
		{from="è",to="ª",offset=-1},
		{from="è",to="°",offset=-1},
		{from="è",to="º",offset=-1},
		{from="é",to='"',offset=-1},
		{from="é",to="'",offset=-1},
		{from="é",to="*",offset=-1},
		{from="é",to="V",offset=-1},
		{from="é",to="\\",offset=-1},
		{from="é",to="ª",offset=-1},
		{from="é",to="°",offset=-1},
		{from="é",to="º",offset=-1},
		{from="ê",to='"',offset=-1},
		{from="ê",to="'",offset=-1},
		{from="ê",to="*",offset=-1},
		{from="ê",to="V",offset=-1},
		{from="ê",to="\\",offset=-1},
		{from="ê",to="ª",offset=-1},
		{from="ê",to="°",offset=-1},
		{from="ê",to="º",offset=-1},
		{from="ë",to='"',offset=-1},
		{from="ë",to="'",offset=-1},
		{from="ë",to="*",offset=-1},
		{from="ë",to="V",offset=-1},
		{from="ë",to="\\",offset=-1},
		{from="ë",to="ª",offset=-1},
		{from="ë",to="°",offset=-1},
		{from="ë",to="º",offset=-1},
		{from="ñ",to='"',offset=-1},
		{from="ñ",to="'",offset=-1},
		{from="ñ",to="*",offset=-1},
		{from="ñ",to="ª",offset=-1},
		{from="ñ",to="°",offset=-1},
		{from="ñ",to="²",offset=-1},
		{from="ñ",to="³",offset=-1},
		{from="ñ",to="¹",offset=-1},
		{from="ñ",to="º",offset=-1},
		{from="ò",to='"',offset=-1},
		{from="ò",to="'",offset=-1},
		{from="ò",to="*",offset=-1},
		{from="ò",to="V",offset=-1},
		{from="ò",to="\\",offset=-1},
		{from="ò",to="ª",offset=-1},
		{from="ò",to="°",offset=-1},
		{from="ò",to="º",offset=-1},
		{from="ó",to='"',offset=-1},
		{from="ó",to="'",offset=-1},
		{from="ó",to="*",offset=-1},
		{from="ó",to="V",offset=-1},
		{from="ó",to="\\",offset=-1},
		{from="ó",to="ª",offset=-1},
		{from="ó",to="°",offset=-1},
		{from="ó",to="º",offset=-1},
		{from="ô",to='"',offset=-1},
		{from="ô",to="'",offset=-1},
		{from="ô",to="*",offset=-1},
		{from="ô",to="V",offset=-1},
		{from="ô",to="\\",offset=-1},
		{from="ô",to="ª",offset=-1},
		{from="ô",to="°",offset=-1},
		{from="ô",to="º",offset=-1},
		{from="õ",to='"',offset=-1},
		{from="õ",to="'",offset=-1},
		{from="õ",to="*",offset=-1},
		{from="õ",to="V",offset=-1},
		{from="õ",to="\\",offset=-1},
		{from="õ",to="ª",offset=-1},
		{from="õ",to="°",offset=-1},
		{from="õ",to="º",offset=-1},
		{from="ö",to='"',offset=-1},
		{from="ö",to="'",offset=-1},
		{from="ö",to="*",offset=-1},
		{from="ö",to="V",offset=-1},
		{from="ö",to="\\",offset=-1},
		{from="ö",to="ª",offset=-1},
		{from="ö",to="°",offset=-1},
		{from="ö",to="º",offset=-1},
		{from="ø",to='"',offset=-1},
		{from="ø",to="'",offset=-1},
		{from="ø",to="*",offset=-1},
		{from="ø",to="V",offset=-1},
		{from="ø",to="\\",offset=-1},
		{from="ø",to="ª",offset=-1},
		{from="ø",to="°",offset=-1},
		{from="ø",to="º",offset=-1},
		{from="þ",to='"',offset=-1},
		{from="þ",to="'",offset=-1},
		{from="þ",to="*",offset=-1},
		{from="þ",to="V",offset=-1},
		{from="þ",to="\\",offset=-1},
		{from="þ",to="ª",offset=-1},
		{from="þ",to="°",offset=-1},
		{from="þ",to="º",offset=-1},
		{from="Ą",to='"',offset=-1},
		{from="Ą",to="'",offset=-1},
		{from="Ą",to="*",offset=-1},
		{from="Ą",to="T",offset=-1},
		{from="Ą",to="V",offset=-1},
		{from="Ą",to="W",offset=-1},
		{from="Ą",to="Y",offset=-1},
		{from="Ą",to="\\",offset=-1},
		{from="Ą",to="v",offset=-1},
		{from="Ą",to="y",offset=-1},
		{from="Ą",to="ª",offset=-1},
		{from="Ą",to="°",offset=-1},
		{from="Ą",to="²",offset=-1},
		{from="Ą",to="³",offset=-1},
		{from="Ą",to="¹",offset=-1},
		{from="Ą",to="º",offset=-1},
		{from="Ą",to="Ý",offset=-1},
		{from="Ą",to="Ÿ",offset=-1},
		{from="ą",to='"',offset=-1},
		{from="ą",to="'",offset=-1},
		{from="ą",to="*",offset=-1},
		{from="ą",to="ª",offset=-1},
		{from="ą",to="°",offset=-1},
		{from="ą",to="²",offset=-1},
		{from="ą",to="³",offset=-1},
		{from="ą",to="¹",offset=-1},
		{from="ą",to="º",offset=-1},
		{from="Ć",to="-",offset=-1},
		{from="Ć",to="«",offset=-1},
		{from="Ć",to="­",offset=-1},
		{from="Ć",to="·",offset=-1},
		{from="Ć",to="»",offset=-1},
		{from="ę",to='"',offset=-1},
		{from="ę",to="'",offset=-1},
		{from="ę",to="*",offset=-1},
		{from="ę",to="V",offset=-1},
		{from="ę",to="\\",offset=-1},
		{from="ę",to="ª",offset=-1},
		{from="ę",to="°",offset=-1},
		{from="ę",to="º",offset=-1},
		{from="Ł",to='"',offset=-1},
		{from="Ł",to="'",offset=-1},
		{from="Ł",to="*",offset=-1},
		{from="Ł",to="-",offset=-1},
		{from="Ł",to="V",offset=-1},
		{from="Ł",to="W",offset=-1},
		{from="Ł",to="Y",offset=-1},
		{from="Ł",to="\\",offset=-1},
		{from="Ł",to="ª",offset=-1},
		{from="Ł",to="«",offset=-1},
		{from="Ł",to="­",offset=-1},
		{from="Ł",to="°",offset=-1},
		{from="Ł",to="²",offset=-1},
		{from="Ł",to="³",offset=-1},
		{from="Ł",to="·",offset=-1},
		{from="Ł",to="¹",offset=-1},
		{from="Ł",to="º",offset=-1},
		{from="Ł",to="»",offset=-1},
		{from="Ł",to="Ý",offset=-1},
		{from="Ł",to="Ÿ",offset=-1},
		{from="ń",to='"',offset=-1},
		{from="ń",to="'",offset=-1},
		{from="ń",to="*",offset=-1},
		{from="ń",to="ª",offset=-1},
		{from="ń",to="°",offset=-1},
		{from="ń",to="²",offset=-1},
		{from="ń",to="³",offset=-1},
		{from="ń",to="¹",offset=-1},
		{from="ń",to="º",offset=-1},
		{from="œ",to='"',offset=-1},
		{from="œ",to="'",offset=-1},
		{from="œ",to="*",offset=-1},
		{from="œ",to="V",offset=-1},
		{from="œ",to="\\",offset=-1},
		{from="œ",to="ª",offset=-1},
		{from="œ",to="°",offset=-1},
		{from="œ",to="º",offset=-1},
		{from="Ÿ",to="&",offset=-1},
		{from="Ÿ",to=",",offset=-1},
		{from="Ÿ",to="-",offset=-1},
		{from="Ÿ",to=".",offset=-1},
		{from="Ÿ",to="/",offset=-1},
		{from="Ÿ",to=":",offset=-1},
		{from="Ÿ",to=";",offset=-1},
		{from="Ÿ",to="@",offset=-1},
		{from="Ÿ",to="A",offset=-1},
		{from="Ÿ",to="C",offset=-1},
		{from="Ÿ",to="G",offset=-1},
		{from="Ÿ",to="J",offset=-1},
		{from="Ÿ",to="O",offset=-1},
		{from="Ÿ",to="Q",offset=-1},
		{from="Ÿ",to="a",offset=-1},
		{from="Ÿ",to="c",offset=-1},
		{from="Ÿ",to="d",offset=-1},
		{from="Ÿ",to="e",offset=-1},
		{from="Ÿ",to="g",offset=-1},
		{from="Ÿ",to="m",offset=-1},
		{from="Ÿ",to="n",offset=-1},
		{from="Ÿ",to="o",offset=-1},
		{from="Ÿ",to="p",offset=-1},
		{from="Ÿ",to="q",offset=-1},
		{from="Ÿ",to="r",offset=-1},
		{from="Ÿ",to="s",offset=-1},
		{from="Ÿ",to="u",offset=-1},
		{from="Ÿ",to="v",offset=-1},
		{from="Ÿ",to="w",offset=-1},
		{from="Ÿ",to="x",offset=-1},
		{from="Ÿ",to="y",offset=-1},
		{from="Ÿ",to="«",offset=-1},
		{from="Ÿ",to="­",offset=-1},
		{from="Ÿ",to="µ",offset=-1},
		{from="Ÿ",to="·",offset=-1},
		{from="Ÿ",to="»",offset=-1},
		{from="Ÿ",to="À",offset=-1},
		{from="Ÿ",to="Á",offset=-1},
		{from="Ÿ",to="Â",offset=-1},
		{from="Ÿ",to="Ã",offset=-1},
		{from="Ÿ",to="Ä",offset=-1},
		{from="Ÿ",to="Å",offset=-1},
		{from="Ÿ",to="Æ",offset=-1},
		{from="Ÿ",to="Ç",offset=-1},
		{from="Ÿ",to="Ò",offset=-1},
		{from="Ÿ",to="Ó",offset=-1},
		{from="Ÿ",to="Ô",offset=-1},
		{from="Ÿ",to="Õ",offset=-1},
		{from="Ÿ",to="Ö",offset=-1},
		{from="Ÿ",to="Ø",offset=-1},
		{from="Ÿ",to="à",offset=-1},
		{from="Ÿ",to="á",offset=-1},
		{from="Ÿ",to="â",offset=-1},
		{from="Ÿ",to="ã",offset=-1},
		{from="Ÿ",to="ä",offset=-1},
		{from="Ÿ",to="å",offset=-1},
		{from="Ÿ",to="æ",offset=-1},
		{from="Ÿ",to="ç",offset=-1},
		{from="Ÿ",to="è",offset=-1},
		{from="Ÿ",to="é",offset=-1},
		{from="Ÿ",to="ê",offset=-1},
		{from="Ÿ",to="ë",offset=-1},
		{from="Ÿ",to="ð",offset=-1},
		{from="Ÿ",to="ñ",offset=-1},
		{from="Ÿ",to="ò",offset=-1},
		{from="Ÿ",to="ó",offset=-1},
		{from="Ÿ",to="ô",offset=-1},
		{from="Ÿ",to="õ",offset=-1},
		{from="Ÿ",to="ö",offset=-1},
		{from="Ÿ",to="ø",offset=-1},
		{from="Ÿ",to="ù",offset=-1},
		{from="Ÿ",to="ú",offset=-1},
		{from="Ÿ",to="û",offset=-1},
		{from="Ÿ",to="ü",offset=-1},
		{from="Ÿ",to="Ą",offset=-1},
		{from="Ÿ",to="ą",offset=-1},
		{from="Ÿ",to="Ć",offset=-1},
		{from="Ÿ",to="ć",offset=-1},
		{from="Ÿ",to="ę",offset=-1},
		{from="Ÿ",to="ń",offset=-1},
		{from="Ÿ",to="Œ",offset=-1},
		{from="Ÿ",to="œ",offset=-1},
	}
}
