return {
	file="lora_regular_14_red.PNG",
	height=23,
	description={
		family="Lora",
		style="Regular",
		size=14
	},
	metrics={
		ascender=18,
		descender=-6,
		height=23
	},
	texture={
		file="lora_regular_14_red.PNG",
		width=284,
		height=252
	},
	chars={
		[" "] = {width=5,x=1,y=17,w=0,h=0,ox=0,oy=0},
		["!"] = {width=5,x=2,y=3,w=3,h=14,ox=1,oy=14},
		['"'] = {width=7,x=6,y=3,w=5,h=4,ox=1,oy=14},
		["#"] = {width=16,x=12,y=3,w=14,h=14,ox=1,oy=14},
		["$"] = {width=10,x=27,y=1,w=9,h=19,ox=1,oy=16},
		["%"] = {width=17,x=37,y=2,w=15,h=16,ox=1,oy=15},
		["&"] = {width=13,x=53,y=3,w=13,h=14,ox=1,oy=14},
		["'"] = {width=4,x=67,y=3,w=2,h=4,ox=1,oy=14},
		["("] = {width=6,x=70,y=2,w=5,h=20,ox=1,oy=15},
		[")"] = {width=6,x=76,y=2,w=5,h=20,ox=0,oy=15},
		["*"] = {width=10,x=82,y=3,w=9,h=8,ox=0,oy=14},
		["+"] = {width=10,x=92,y=7,w=9,h=9,ox=0,oy=10},
		[","] = {width=5,x=102,y=15,w=3,h=5,ox=1,oy=2},
		["-"] = {width=9,x=106,y=10,w=7,h=2,ox=1,oy=7},
		["."] = {width=5,x=114,y=15,w=3,h=2,ox=1,oy=2},
		["/"] = {width=13,x=118,y=2,w=13,h=20,ox=0,oy=15},
		["0"] = {width=12,x=132,y=3,w=10,h=14,ox=1,oy=14},
		["1"] = {width=7,x=143,y=3,w=7,h=14,ox=0,oy=14},
		["2"] = {width=10,x=151,y=3,w=9,h=14,ox=0,oy=14},
		["3"] = {width=11,x=161,y=3,w=9,h=14,ox=1,oy=14},
		["4"] = {width=10,x=171,y=3,w=10,h=14,ox=0,oy=14},
		["5"] = {width=10,x=182,y=2,w=9,h=15,ox=0,oy=15},
		["6"] = {width=11,x=192,y=3,w=9,h=14,ox=1,oy=14},
		["7"] = {width=9,x=202,y=3,w=8,h=15,ox=0,oy=14},
		["8"] = {width=11,x=211,y=3,w=9,h=14,ox=1,oy=14},
		["9"] = {width=11,x=221,y=3,w=9,h=14,ox=1,oy=14},
		[":"] = {width=5,x=231,y=7,w=3,h=10,ox=1,oy=10},
		[";"] = {width=5,x=235,y=7,w=3,h=13,ox=1,oy=10},
		["<"] = {width=10,x=239,y=6,w=8,h=9,ox=1,oy=11},
		["="] = {width=11,x=248,y=7,w=8,h=7,ox=1,oy=10},
		[">"] = {width=10,x=257,y=6,w=8,h=9,ox=1,oy=11},
		["?"] = {width=9,x=266,y=3,w=9,h=14,ox=0,oy=14},
		["@"] = {width=15,x=1,y=26,w=13,h=14,ox=1,oy=12},
		["A"] = {width=12,x=15,y=24,w=13,h=14,ox=0,oy=14},
		["B"] = {width=12,x=29,y=24,w=11,h=14,ox=0,oy=14},
		["C"] = {width=13,x=41,y=24,w=12,h=14,ox=1,oy=14},
		["D"] = {width=14,x=54,y=24,w=13,h=14,ox=0,oy=14},
		["E"] = {width=12,x=68,y=24,w=10,h=14,ox=1,oy=14},
		["F"] = {width=10,x=79,y=24,w=9,h=14,ox=1,oy=14},
		["G"] = {width=14,x=89,y=24,w=13,h=14,ox=1,oy=14},
		["H"] = {width=15,x=103,y=24,w=13,h=14,ox=1,oy=14},
		["I"] = {width=6,x=117,y=24,w=5,h=14,ox=0,oy=14},
		["J"] = {width=7,x=123,y=24,w=7,h=14,ox=0,oy=14},
		["K"] = {width=13,x=131,y=24,w=13,h=14,ox=0,oy=14},
		["L"] = {width=11,x=145,y=24,w=10,h=14,ox=1,oy=14},
		["M"] = {width=17,x=156,y=24,w=18,h=14,ox=0,oy=14},
		["N"] = {width=14,x=175,y=24,w=14,h=14,ox=0,oy=14},
		["O"] = {width=15,x=190,y=24,w=13,h=14,ox=1,oy=14},
		["P"] = {width=12,x=204,y=24,w=11,h=14,ox=0,oy=14},
		["Q"] = {width=15,x=216,y=24,w=14,h=18,ox=1,oy=14},
		["R"] = {width=12,x=231,y=23,w=12,h=15,ox=0,oy=15},
		["S"] = {width=10,x=244,y=24,w=9,h=14,ox=1,oy=14},
		["T"] = {width=12,x=254,y=24,w=12,h=14,ox=0,oy=14},
		["U"] = {width=14,x=267,y=24,w=15,h=14,ox=0,oy=14},
		["V"] = {width=12,x=1,y=45,w=14,h=14,ox=-1,oy=14},
		["W"] = {width=19,x=16,y=44,w=21,h=15,ox=-1,oy=15},
		["X"] = {width=12,x=38,y=45,w=14,h=14,ox=-1,oy=14},
		["Y"] = {width=12,x=53,y=45,w=13,h=14,ox=-1,oy=14},
		["Z"] = {width=12,x=67,y=45,w=11,h=14,ox=0,oy=14},
		["["] = {width=7,x=79,y=44,w=5,h=20,ox=2,oy=15},
		["\\"] = {width=13,x=85,y=44,w=13,h=20,ox=0,oy=15},
		["]"] = {width=7,x=99,y=44,w=7,h=20,ox=-1,oy=15},
		["^"] = {width=16,x=107,y=45,w=13,h=6,ox=1,oy=14},
		["_"] = {width=14,x=121,y=60,w=12,h=1,ox=1,oy=-1},
		["`"] = {width=5,x=134,y=44,w=3,h=4,ox=1,oy=15},
		["a"] = {width=10,x=138,y=49,w=9,h=10,ox=1,oy=10},
		["b"] = {width=11,x=148,y=44,w=11,h=15,ox=0,oy=15},
		["c"] = {width=10,x=160,y=49,w=9,h=10,ox=1,oy=10},
		["d"] = {width=11,x=170,y=44,w=10,h=15,ox=1,oy=15},
		["e"] = {width=10,x=181,y=49,w=8,h=10,ox=1,oy=10},
		["f"] = {width=6,x=190,y=44,w=7,h=15,ox=0,oy=15},
		["g"] = {width=11,x=198,y=48,w=10,h=16,ox=1,oy=11},
		["h"] = {width=11,x=209,y=44,w=11,h=15,ox=0,oy=15},
		["i"] = {width=5,x=221,y=45,w=5,h=14,ox=0,oy=14},
		["j"] = {width=5,x=227,y=45,w=6,h=19,ox=-1,oy=14},
		["k"] = {width=10,x=234,y=44,w=10,h=15,ox=0,oy=15},
		["l"] = {width=5,x=245,y=43,w=5,h=16,ox=0,oy=16},
		["m"] = {width=17,x=251,y=49,w=17,h=10,ox=0,oy=10},
		["n"] = {width=11,x=269,y=49,w=11,h=10,ox=0,oy=10},
		["o"] = {width=11,x=1,y=70,w=10,h=10,ox=1,oy=10},
		["p"] = {width=11,x=12,y=70,w=11,h=15,ox=0,oy=10},
		["q"] = {width=11,x=24,y=70,w=10,h=15,ox=1,oy=10},
		["r"] = {width=8,x=35,y=70,w=8,h=10,ox=0,oy=10},
		["s"] = {width=9,x=44,y=70,w=7,h=10,ox=1,oy=10},
		["t"] = {width=7,x=52,y=67,w=7,h=13,ox=0,oy=13},
		["u"] = {width=11,x=60,y=70,w=12,h=10,ox=0,oy=10},
		["v"] = {width=10,x=73,y=70,w=10,h=10,ox=0,oy=10},
		["w"] = {width=15,x=84,y=70,w=17,h=10,ox=-1,oy=10},
		["x"] = {width=10,x=102,y=70,w=10,h=10,ox=0,oy=10},
		["y"] = {width=10,x=113,y=70,w=10,h=15,ox=0,oy=10},
		["z"] = {width=9,x=124,y=70,w=9,h=10,ox=0,oy=10},
		["{"] = {width=6,x=134,y=65,w=7,h=20,ox=0,oy=15},
		["|"] = {width=4,x=142,y=65,w=3,h=20,ox=1,oy=15},
		["}"] = {width=6,x=146,y=65,w=6,h=20,ox=0,oy=15},
		["~"] = {width=11,x=153,y=73,w=8,h=3,ox=1,oy=7},
		[" "] = {width=5,x=162,y=80,w=0,h=0,ox=0,oy=0},
		["¡"] = {width=5,x=163,y=70,w=3,h=14,ox=1,oy=10},
		["¢"] = {width=10,x=167,y=68,w=9,h=14,ox=1,oy=12},
		["£"] = {width=10,x=177,y=66,w=10,h=14,ox=0,oy=14},
		["¤"] = {width=10,x=188,y=70,w=9,h=9,ox=1,oy=10},
		["¥"] = {width=13,x=198,y=66,w=13,h=14,ox=0,oy=14},
		["¦"] = {width=5,x=212,y=65,w=2,h=20,ox=2,oy=15},
		["§"] = {width=10,x=215,y=65,w=8,h=19,ox=1,oy=15},
		["¨"] = {width=7,x=224,y=66,w=5,h=2,ox=1,oy=14},
		["©"] = {width=17,x=230,y=65,w=15,h=15,ox=1,oy=15},
		["ª"] = {width=8,x=246,y=66,w=7,h=6,ox=1,oy=14},
		["«"] = {width=10,x=254,y=69,w=9,h=11,ox=1,oy=11},
		["¬"] = {width=11,x=264,y=74,w=8,h=4,ox=1,oy=6},
		["­"] = {width=9,x=273,y=73,w=7,h=2,ox=1,oy=7},
		["®"] = {width=17,x=1,y=89,w=15,h=15,ox=1,oy=15},
		["¯"] = {width=7,x=17,y=90,w=5,h=2,ox=1,oy=14},
		["°"] = {width=8,x=23,y=90,w=6,h=6,ox=1,oy=14},
		["±"] = {width=11,x=30,y=94,w=9,h=10,ox=1,oy=10},
		["²"] = {width=7,x=40,y=90,w=5,h=8,ox=1,oy=14},
		["³"] = {width=7,x=46,y=90,w=5,h=8,ox=1,oy=14},
		["´"] = {width=5,x=52,y=89,w=3,h=4,ox=1,oy=15},
		["µ"] = {width=12,x=56,y=94,w=11,h=15,ox=1,oy=10},
		["¶"] = {width=10,x=68,y=90,w=8,h=19,ox=0,oy=14},
		["·"] = {width=5,x=77,y=97,w=3,h=2,ox=1,oy=7},
		["¸"] = {width=6,x=81,y=104,w=5,h=5,ox=0,oy=0},
		["¹"] = {width=5,x=87,y=90,w=5,h=8,ox=0,oy=14},
		["º"] = {width=8,x=93,y=90,w=6,h=6,ox=1,oy=14},
		["»"] = {width=10,x=100,y=93,w=9,h=11,ox=0,oy=11},
		["¼"] = {width=15,x=110,y=90,w=15,h=14,ox=0,oy=14},
		["½"] = {width=15,x=126,y=90,w=14,h=14,ox=0,oy=14},
		["¾"] = {width=15,x=141,y=90,w=15,h=14,ox=1,oy=14},
		["¿"] = {width=9,x=157,y=94,w=9,h=14,ox=0,oy=10},
		["À"] = {width=12,x=167,y=86,w=13,h=18,ox=0,oy=18},
		["Á"] = {width=12,x=181,y=86,w=13,h=18,ox=0,oy=18},
		["Â"] = {width=12,x=195,y=86,w=13,h=18,ox=0,oy=18},
		["Ã"] = {width=12,x=209,y=86,w=13,h=18,ox=0,oy=18},
		["Ä"] = {width=12,x=223,y=87,w=13,h=17,ox=0,oy=17},
		["Å"] = {width=12,x=237,y=86,w=13,h=18,ox=0,oy=18},
		["Æ"] = {width=18,x=251,y=90,w=18,h=14,ox=-1,oy=14},
		["Ç"] = {width=13,x=270,y=90,w=12,h=19,ox=1,oy=14},
		["È"] = {width=12,x=1,y=110,w=10,h=18,ox=1,oy=18},
		["É"] = {width=12,x=12,y=110,w=10,h=18,ox=1,oy=18},
		["Ê"] = {width=13,x=23,y=110,w=10,h=18,ox=2,oy=18},
		["Ë"] = {width=12,x=34,y=111,w=10,h=17,ox=1,oy=17},
		["Ì"] = {width=6,x=45,y=110,w=5,h=18,ox=0,oy=18},
		["Í"] = {width=6,x=51,y=110,w=6,h=18,ox=0,oy=18},
		["Î"] = {width=6,x=58,y=110,w=7,h=18,ox=0,oy=18},
		["Ï"] = {width=6,x=66,y=111,w=7,h=17,ox=0,oy=17},
		["Ð"] = {width=14,x=74,y=114,w=14,h=14,ox=-1,oy=14},
		["Ñ"] = {width=15,x=89,y=110,w=14,h=18,ox=0,oy=18},
		["Ò"] = {width=15,x=104,y=110,w=13,h=18,ox=1,oy=18},
		["Ó"] = {width=15,x=118,y=110,w=13,h=18,ox=1,oy=18},
		["Ô"] = {width=15,x=132,y=110,w=13,h=18,ox=1,oy=18},
		["Õ"] = {width=15,x=146,y=110,w=13,h=18,ox=1,oy=18},
		["Ö"] = {width=15,x=160,y=111,w=13,h=17,ox=1,oy=17},
		["×"] = {width=10,x=174,y=117,w=8,h=10,ox=1,oy=11},
		["Ø"] = {width=15,x=183,y=113,w=13,h=17,ox=1,oy=15},
		["Ù"] = {width=14,x=197,y=110,w=15,h=18,ox=0,oy=18},
		["Ú"] = {width=14,x=213,y=110,w=15,h=18,ox=0,oy=18},
		["Û"] = {width=14,x=229,y=110,w=15,h=18,ox=0,oy=18},
		["Ü"] = {width=14,x=245,y=111,w=15,h=17,ox=0,oy=17},
		["Ý"] = {width=12,x=261,y=110,w=13,h=18,ox=-1,oy=18},
		["Þ"] = {width=11,x=1,y=133,w=11,h=14,ox=0,oy=14},
		["ß"] = {width=13,x=13,y=132,w=13,h=15,ox=0,oy=15},
		["à"] = {width=10,x=27,y=132,w=9,h=15,ox=1,oy=15},
		["á"] = {width=10,x=37,y=132,w=9,h=15,ox=1,oy=15},
		["â"] = {width=10,x=47,y=132,w=9,h=15,ox=1,oy=15},
		["ã"] = {width=10,x=57,y=133,w=9,h=14,ox=1,oy=14},
		["ä"] = {width=10,x=67,y=133,w=9,h=14,ox=1,oy=14},
		["å"] = {width=10,x=77,y=132,w=9,h=15,ox=1,oy=15},
		["æ"] = {width=15,x=87,y=137,w=13,h=10,ox=1,oy=10},
		["ç"] = {width=10,x=101,y=137,w=9,h=15,ox=1,oy=10},
		["è"] = {width=10,x=111,y=132,w=8,h=15,ox=1,oy=15},
		["é"] = {width=10,x=120,y=132,w=8,h=15,ox=1,oy=15},
		["ê"] = {width=10,x=129,y=132,w=8,h=15,ox=1,oy=15},
		["ë"] = {width=10,x=138,y=133,w=8,h=14,ox=1,oy=14},
		["ì"] = {width=5,x=147,y=132,w=5,h=15,ox=0,oy=15},
		["í"] = {width=5,x=153,y=132,w=5,h=15,ox=0,oy=15},
		["î"] = {width=5,x=159,y=132,w=5,h=15,ox=0,oy=15},
		["ï"] = {width=5,x=165,y=133,w=5,h=14,ox=0,oy=14},
		["ð"] = {width=11,x=171,y=131,w=9,h=16,ox=1,oy=16},
		["ñ"] = {width=12,x=181,y=133,w=11,h=14,ox=0,oy=14},
		["ò"] = {width=11,x=193,y=132,w=10,h=15,ox=1,oy=15},
		["ó"] = {width=11,x=204,y=132,w=10,h=15,ox=1,oy=15},
		["ô"] = {width=11,x=215,y=132,w=10,h=15,ox=1,oy=15},
		["õ"] = {width=11,x=226,y=133,w=10,h=14,ox=1,oy=14},
		["ö"] = {width=11,x=237,y=133,w=10,h=14,ox=1,oy=14},
		["÷"] = {width=5,x=248,y=137,w=2,h=9,ox=1,oy=10},
		["ø"] = {width=11,x=251,y=136,w=10,h=13,ox=1,oy=11},
		["ù"] = {width=11,x=262,y=132,w=12,h=15,ox=0,oy=15},
		["ú"] = {width=11,x=1,y=156,w=12,h=15,ox=0,oy=15},
		["û"] = {width=11,x=14,y=156,w=12,h=15,ox=0,oy=15},
		["ü"] = {width=11,x=27,y=157,w=12,h=14,ox=0,oy=14},
		["ý"] = {width=10,x=40,y=156,w=10,h=20,ox=0,oy=15},
		["þ"] = {width=11,x=51,y=156,w=11,h=20,ox=0,oy=15},
		["ÿ"] = {width=10,x=63,y=157,w=10,h=19,ox=0,oy=14},
		["Ā"] = {width=12,x=74,y=153,w=13,h=18,ox=0,oy=18},
		["ā"] = {width=10,x=88,y=157,w=9,h=14,ox=1,oy=14},
		["Ă"] = {width=12,x=98,y=153,w=13,h=18,ox=0,oy=18},
		["ă"] = {width=10,x=112,y=157,w=9,h=14,ox=1,oy=14},
		["Ą"] = {width=12,x=122,y=157,w=13,h=19,ox=-1,oy=14},
		["ą"] = {width=10,x=136,y=161,w=10,h=15,ox=1,oy=10},
		["Ć"] = {width=13,x=147,y=153,w=12,h=18,ox=1,oy=18},
		["ć"] = {width=10,x=160,y=156,w=9,h=15,ox=1,oy=15},
		["Č"] = {width=13,x=170,y=153,w=12,h=18,ox=1,oy=18},
		["č"] = {width=10,x=183,y=155,w=9,h=16,ox=1,oy=16},
		["Ď"] = {width=14,x=193,y=153,w=13,h=18,ox=0,oy=18},
		["ď"] = {width=13,x=207,y=156,w=13,h=16,ox=0,oy=15},
		["Đ"] = {width=14,x=221,y=157,w=14,h=14,ox=-1,oy=14},
		["đ"] = {width=12,x=236,y=156,w=11,h=15,ox=1,oy=15},
		["Ē"] = {width=12,x=248,y=153,w=10,h=18,ox=1,oy=18},
		["ē"] = {width=10,x=259,y=157,w=8,h=14,ox=1,oy=14},
		["Ė"] = {width=12,x=268,y=153,w=10,h=18,ox=1,oy=18},
		["ė"] = {width=10,x=1,y=182,w=8,h=14,ox=1,oy=14},
		["Ę"] = {width=12,x=10,y=182,w=12,h=19,ox=0,oy=14},
		["ę"] = {width=11,x=23,y=186,w=9,h=15,ox=1,oy=10},
		["Ě"] = {width=12,x=33,y=178,w=11,h=18,ox=1,oy=18},
		["ě"] = {width=10,x=45,y=180,w=8,h=16,ox=1,oy=16},
		["Ğ"] = {width=14,x=54,y=178,w=13,h=18,ox=1,oy=18},
		["ğ"] = {width=11,x=68,y=182,w=10,h=19,ox=1,oy=14},
		["Ģ"] = {width=14,x=79,y=182,w=13,h=19,ox=1,oy=14},
		["ģ"] = {width=12,x=93,y=181,w=11,h=20,ox=0,oy=15},
		["Ī"] = {width=6,x=105,y=178,w=6,h=18,ox=0,oy=18},
		["ī"] = {width=5,x=112,y=182,w=6,h=14,ox=0,oy=14},
		["Į"] = {width=6,x=119,y=182,w=6,h=19,ox=1,oy=14},
		["į"] = {width=5,x=126,y=182,w=6,h=19,ox=0,oy=14},
		["İ"] = {width=6,x=133,y=178,w=5,h=18,ox=0,oy=18},
		["ı"] = {width=5,x=139,y=186,w=5,h=10,ox=0,oy=10},
		["Ķ"] = {width=13,x=145,y=182,w=14,h=19,ox=0,oy=14},
		["ķ"] = {width=10,x=160,y=181,w=11,h=20,ox=0,oy=15},
		["Ĺ"] = {width=11,x=172,y=178,w=10,h=18,ox=1,oy=18},
		["ĺ"] = {width=5,x=183,y=177,w=5,h=19,ox=0,oy=19},
		["Ļ"] = {width=11,x=189,y=182,w=11,h=19,ox=1,oy=14},
		["ļ"] = {width=5,x=201,y=180,w=5,h=21,ox=0,oy=16},
		["Ľ"] = {width=11,x=207,y=182,w=11,h=14,ox=0,oy=14},
		["ľ"] = {width=6,x=219,y=181,w=7,h=15,ox=0,oy=15},
		["Ł"] = {width=11,x=227,y=182,w=10,h=14,ox=1,oy=14},
		["ł"] = {width=6,x=238,y=181,w=6,h=15,ox=0,oy=15},
		["Ń"] = {width=14,x=245,y=178,w=14,h=18,ox=0,oy=18},
		["ń"] = {width=12,x=260,y=181,w=11,h=15,ox=0,oy=15},
		["Ņ"] = {width=14,x=1,y=206,w=14,h=19,ox=0,oy=14},
		["ņ"] = {width=12,x=16,y=210,w=11,h=15,ox=0,oy=10},
		["Ň"] = {width=14,x=28,y=202,w=14,h=18,ox=0,oy=18},
		["ň"] = {width=12,x=43,y=204,w=11,h=16,ox=0,oy=16},
		["ŉ"] = {width=12,x=55,y=203,w=11,h=17,ox=0,oy=17},
		["Ō"] = {width=15,x=67,y=202,w=13,h=18,ox=1,oy=18},
		["ō"] = {width=11,x=81,y=206,w=10,h=14,ox=1,oy=14},
		["Ő"] = {width=15,x=92,y=202,w=13,h=18,ox=1,oy=18},
		["ő"] = {width=11,x=106,y=206,w=10,h=14,ox=1,oy=14},
		["Œ"] = {width=19,x=117,y=206,w=18,h=14,ox=1,oy=14},
		["œ"] = {width=17,x=136,y=210,w=15,h=10,ox=1,oy=10},
		["Ŕ"] = {width=12,x=152,y=202,w=12,h=18,ox=0,oy=18},
		["ŕ"] = {width=8,x=165,y=205,w=8,h=15,ox=0,oy=15},
		["Ŗ"] = {width=12,x=174,y=205,w=12,h=20,ox=0,oy=15},
		["ŗ"] = {width=8,x=187,y=210,w=9,h=15,ox=0,oy=10},
		["Ř"] = {width=12,x=197,y=202,w=12,h=18,ox=0,oy=18},
		["ř"] = {width=8,x=210,y=204,w=9,h=16,ox=0,oy=16},
		["Ś"] = {width=11,x=220,y=202,w=9,h=18,ox=1,oy=18},
		["ś"] = {width=9,x=230,y=205,w=7,h=15,ox=1,oy=15},
		["Ş"] = {width=11,x=238,y=206,w=11,h=19,ox=0,oy=14},
		["ş"] = {width=10,x=250,y=210,w=9,h=15,ox=0,oy=10},
		["Š"] = {width=11,x=260,y=202,w=9,h=18,ox=1,oy=18},
		["š"] = {width=9,x=270,y=204,w=7,h=16,ox=1,oy=16},
		["Ţ"] = {width=12,x=1,y=231,w=12,h=19,ox=0,oy=14},
		["ţ"] = {width=8,x=14,y=232,w=8,h=18,ox=0,oy=13},
		["Ť"] = {width=12,x=23,y=227,w=13,h=18,ox=0,oy=18},
		["ť"] = {width=7,x=37,y=230,w=8,h=15,ox=0,oy=15},
		["Ū"] = {width=14,x=46,y=227,w=15,h=18,ox=0,oy=18},
		["ū"] = {width=11,x=62,y=231,w=12,h=14,ox=0,oy=14},
		["Ů"] = {width=14,x=75,y=226,w=15,h=19,ox=0,oy=19},
		["ů"] = {width=11,x=91,y=230,w=12,h=15,ox=0,oy=15},
		["Ű"] = {width=14,x=104,y=227,w=15,h=18,ox=0,oy=18},
		["ű"] = {width=11,x=120,y=231,w=12,h=14,ox=0,oy=14},
		["Ų"] = {width=14,x=133,y=231,w=14,h=19,ox=0,oy=14},
		["ų"] = {width=12,x=148,y=235,w=12,h=15,ox=0,oy=10},
		["Ÿ"] = {width=12,x=161,y=228,w=13,h=17,ox=-1,oy=17},
		["Ź"] = {width=12,x=175,y=227,w=11,h=18,ox=0,oy=18},
		["ź"] = {width=10,x=187,y=230,w=9,h=15,ox=0,oy=15},
		["Ż"] = {width=12,x=197,y=227,w=11,h=18,ox=0,oy=18},
		["ż"] = {width=10,x=209,y=231,w=9,h=14,ox=0,oy=14},
		["Ž"] = {width=12,x=219,y=227,w=11,h=18,ox=0,oy=18},
		["ž"] = {width=10,x=231,y=229,w=9,h=16,ox=0,oy=16},
		["ƒ"] = {width=7,x=241,y=230,w=9,h=20,ox=-2,oy=15},
	},
	kernings={
		{from='"',to=",",offset=-2},
		{from='"',to=".",offset=-2},
		{from='"',to="/",offset=-2},
		{from='"',to="4",offset=-1},
		{from='"',to="A",offset=-1},
		{from='"',to="«",offset=-1},
		{from='"',to="À",offset=-1},
		{from='"',to="Á",offset=-1},
		{from='"',to="Â",offset=-1},
		{from='"',to="Ã",offset=-1},
		{from='"',to="Ä",offset=-1},
		{from='"',to="Å",offset=-1},
		{from='"',to="Æ",offset=-1},
		{from="&",to='"',offset=-1},
		{from="&",to="'",offset=-1},
		{from="&",to="A",offset=1},
		{from="&",to="J",offset=1},
		{from="&",to="À",offset=1},
		{from="&",to="Á",offset=1},
		{from="&",to="Â",offset=1},
		{from="&",to="Ã",offset=1},
		{from="&",to="Ä",offset=1},
		{from="&",to="Å",offset=1},
		{from="&",to="Æ",offset=1},
		{from="'",to=",",offset=-1},
		{from="'",to=".",offset=-1},
		{from="'",to="/",offset=-1},
		{from="'",to="4",offset=-1},
		{from="'",to="A",offset=-1},
		{from="'",to="«",offset=-1},
		{from="'",to="À",offset=-1},
		{from="'",to="Á",offset=-1},
		{from="'",to="Â",offset=-1},
		{from="'",to="Ã",offset=-1},
		{from="'",to="Ä",offset=-1},
		{from="'",to="Å",offset=-1},
		{from="'",to="Æ",offset=-1},
		{from="(",to="V",offset=1},
		{from="(",to="c",offset=-1},
		{from="(",to="e",offset=-1},
		{from="(",to="j",offset=1},
		{from="(",to="o",offset=-1},
		{from="(",to="ç",offset=-1},
		{from="(",to="è",offset=-1},
		{from="(",to="é",offset=-1},
		{from="(",to="ê",offset=-1},
		{from="(",to="ë",offset=-1},
		{from="(",to="ò",offset=-1},
		{from="(",to="ó",offset=-1},
		{from="(",to="ô",offset=-1},
		{from="(",to="õ",offset=-1},
		{from="(",to="ö",offset=-1},
		{from="(",to="ø",offset=-1},
		{from="(",to="œ",offset=-1},
		{from="*",to="Æ",offset=-1},
		{from="+",to="7",offset=-1},
		{from=",",to='"',offset=-2},
		{from=",",to="'",offset=-1},
		{from=",",to="T",offset=-1},
		{from=",",to="V",offset=-1},
		{from=",",to="W",offset=-1},
		{from=",",to="Y",offset=-1},
		{from=",",to="v",offset=-1},
		{from=",",to="w",offset=-1},
		{from=",",to="y",offset=-1},
		{from=",",to="Ý",offset=-1},
		{from=",",to="ý",offset=-1},
		{from=",",to="ÿ",offset=-1},
		{from=",",to="Ÿ",offset=-1},
		{from="-",to="7",offset=-1},
		{from="-",to="T",offset=-1},
		{from="-",to="X",offset=-1},
		{from="-",to="Y",offset=-1},
		{from="-",to="Æ",offset=-1},
		{from="-",to="Ý",offset=-1},
		{from="-",to="Ÿ",offset=-1},
		{from=".",to='"',offset=-2},
		{from=".",to="'",offset=-1},
		{from=".",to="T",offset=-1},
		{from=".",to="V",offset=-1},
		{from=".",to="W",offset=-1},
		{from=".",to="Y",offset=-1},
		{from=".",to="v",offset=-1},
		{from=".",to="w",offset=-1},
		{from=".",to="y",offset=-1},
		{from=".",to="Ý",offset=-1},
		{from=".",to="ý",offset=-1},
		{from=".",to="ÿ",offset=-1},
		{from=".",to="Ÿ",offset=-1},
		{from="/",to="4",offset=-1},
		{from="/",to="A",offset=-1},
		{from="/",to="a",offset=-1},
		{from="/",to="c",offset=-1},
		{from="/",to="d",offset=-1},
		{from="/",to="e",offset=-1},
		{from="/",to="g",offset=-1},
		{from="/",to="o",offset=-1},
		{from="/",to="q",offset=-1},
		{from="/",to="s",offset=-1},
		{from="/",to="À",offset=-1},
		{from="/",to="Á",offset=-1},
		{from="/",to="Â",offset=-1},
		{from="/",to="Ã",offset=-1},
		{from="/",to="Ä",offset=-1},
		{from="/",to="Å",offset=-1},
		{from="/",to="Æ",offset=-1},
		{from="/",to="à",offset=-1},
		{from="/",to="á",offset=-1},
		{from="/",to="â",offset=-1},
		{from="/",to="ã",offset=-1},
		{from="/",to="ä",offset=-1},
		{from="/",to="å",offset=-1},
		{from="/",to="æ",offset=-1},
		{from="/",to="ç",offset=-1},
		{from="/",to="è",offset=-1},
		{from="/",to="é",offset=-1},
		{from="/",to="ê",offset=-1},
		{from="/",to="ë",offset=-1},
		{from="/",to="ò",offset=-1},
		{from="/",to="ó",offset=-1},
		{from="/",to="ô",offset=-1},
		{from="/",to="õ",offset=-1},
		{from="/",to="ö",offset=-1},
		{from="/",to="ø",offset=-1},
		{from="/",to="œ",offset=-1},
		{from="/",to="š",offset=-1},
		{from="0",to="/",offset=-1},
		{from="3",to="/",offset=-1},
		{from="5",to="/",offset=-1},
		{from="6",to="/",offset=-1},
		{from="7",to=",",offset=-1},
		{from="7",to=".",offset=-1},
		{from="7",to="/",offset=-1},
		{from="7",to="Æ",offset=-1},
		{from="8",to="/",offset=-1},
		{from="9",to="/",offset=-1},
		{from="A",to='"',offset=-1},
		{from="A",to="'",offset=-1},
		{from="A",to="J",offset=1},
		{from="A",to="V",offset=-1},
		{from="A",to="W",offset=-1},
		{from="A",to="X",offset=1},
		{from="A",to="\\",offset=-1},
		{from="A",to="´",offset=-1},
		{from="A",to="À",offset=1},
		{from="A",to="Á",offset=1},
		{from="A",to="Â",offset=1},
		{from="A",to="Ã",offset=1},
		{from="A",to="Ä",offset=1},
		{from="A",to="Å",offset=1},
		{from="A",to="Æ",offset=1},
		{from="B",to="/",offset=-1},
		{from="B",to="]",offset=-1},
		{from="D",to="/",offset=-1},
		{from="D",to="]",offset=-1},
		{from="D",to="Æ",offset=-1},
		{from="G",to="/",offset=-1},
		{from="J",to="/",offset=-1},
		{from="K",to="-",offset=-1},
		{from="K",to="J",offset=1},
		{from="K",to="v",offset=-1},
		{from="K",to="w",offset=-1},
		{from="K",to="­",offset=-1},
		{from="L",to='"',offset=-1},
		{from="L",to="'",offset=-1},
		{from="L",to="*",offset=-1},
		{from="L",to="-",offset=-1},
		{from="L",to="T",offset=-1},
		{from="L",to="V",offset=-1},
		{from="L",to="W",offset=-1},
		{from="L",to="Y",offset=-1},
		{from="L",to="\\",offset=-1},
		{from="L",to="]",offset=-1},
		{from="L",to="v",offset=-1},
		{from="L",to="w",offset=-1},
		{from="L",to="ª",offset=-1},
		{from="L",to="­",offset=-1},
		{from="L",to="·",offset=-2},
		{from="L",to="Ý",offset=-1},
		{from="L",to="Ÿ",offset=-1},
		{from="N",to="/",offset=-1},
		{from="O",to="/",offset=-1},
		{from="O",to="]",offset=-1},
		{from="O",to="Æ",offset=-1},
		{from="P",to=",",offset=-1},
		{from="P",to=".",offset=-1},
		{from="P",to="/",offset=-1},
		{from="P",to="J",offset=-1},
		{from="P",to="Æ",offset=-1},
		{from="Q",to="/",offset=-1},
		{from="Q",to="j",offset=2},
		{from="Q",to="Æ",offset=-1},
		{from="R",to="A",offset=1},
		{from="R",to="À",offset=1},
		{from="R",to="Á",offset=1},
		{from="R",to="Â",offset=1},
		{from="R",to="Ã",offset=1},
		{from="R",to="Ä",offset=1},
		{from="R",to="Å",offset=1},
		{from="R",to="Æ",offset=1},
		{from="S",to="/",offset=-1},
		{from="T",to=",",offset=-1},
		{from="T",to="-",offset=-1},
		{from="T",to=".",offset=-1},
		{from="T",to="/",offset=-1},
		{from="T",to="c",offset=-1},
		{from="T",to="d",offset=-1},
		{from="T",to="e",offset=-1},
		{from="T",to="g",offset=-1},
		{from="T",to="o",offset=-1},
		{from="T",to="q",offset=-1},
		{from="T",to="z",offset=-1},
		{from="T",to="«",offset=-1},
		{from="T",to="­",offset=-1},
		{from="T",to="Æ",offset=-1},
		{from="T",to="ç",offset=-1},
		{from="T",to="è",offset=-1},
		{from="T",to="é",offset=-1},
		{from="T",to="ê",offset=-1},
		{from="T",to="ë",offset=-1},
		{from="T",to="ð",offset=-1},
		{from="T",to="ò",offset=-1},
		{from="T",to="ó",offset=-1},
		{from="T",to="ô",offset=-1},
		{from="T",to="õ",offset=-1},
		{from="T",to="ö",offset=-1},
		{from="T",to="ø",offset=-1},
		{from="T",to="œ",offset=-1},
		{from="T",to="ž",offset=-1},
		{from="U",to=",",offset=-1},
		{from="U",to="/",offset=-1},
		{from="U",to="Æ",offset=-1},
		{from="V",to=")",offset=1},
		{from="V",to=",",offset=-1},
		{from="V",to=".",offset=-1},
		{from="V",to="/",offset=-1},
		{from="V",to=":",offset=-1},
		{from="V",to=";",offset=-1},
		{from="V",to="A",offset=-1},
		{from="V",to="W",offset=1},
		{from="V",to="X",offset=1},
		{from="V",to="Y",offset=1},
		{from="V",to="]",offset=1},
		{from="V",to="b",offset=1},
		{from="V",to="c",offset=-1},
		{from="V",to="d",offset=-1},
		{from="V",to="e",offset=-1},
		{from="V",to="g",offset=-1},
		{from="V",to="o",offset=-1},
		{from="V",to="q",offset=-1},
		{from="V",to="z",offset=-1},
		{from="V",to="À",offset=-1},
		{from="V",to="Á",offset=-1},
		{from="V",to="Â",offset=-1},
		{from="V",to="Ã",offset=-1},
		{from="V",to="Ä",offset=-1},
		{from="V",to="Å",offset=-1},
		{from="V",to="Æ",offset=-1},
		{from="V",to="Ý",offset=1},
		{from="V",to="ç",offset=-1},
		{from="V",to="è",offset=-1},
		{from="V",to="é",offset=-1},
		{from="V",to="ê",offset=-1},
		{from="V",to="ë",offset=-1},
		{from="V",to="ì",offset=1},
		{from="V",to="î",offset=1},
		{from="V",to="ï",offset=1},
		{from="V",to="ò",offset=-1},
		{from="V",to="ó",offset=-1},
		{from="V",to="ô",offset=-1},
		{from="V",to="õ",offset=-1},
		{from="V",to="ö",offset=-1},
		{from="V",to="ø",offset=-1},
		{from="V",to="þ",offset=1},
		{from="V",to="œ",offset=-1},
		{from="V",to="Ÿ",offset=1},
		{from="V",to="ž",offset=-1},
		{from="W",to=",",offset=-1},
		{from="W",to=".",offset=-1},
		{from="W",to="/",offset=-1},
		{from="W",to="A",offset=-1},
		{from="W",to="V",offset=1},
		{from="W",to="X",offset=1},
		{from="W",to="Y",offset=1},
		{from="W",to="]",offset=1},
		{from="W",to="a",offset=-1},
		{from="W",to="b",offset=1},
		{from="W",to="c",offset=-1},
		{from="W",to="d",offset=-1},
		{from="W",to="e",offset=-1},
		{from="W",to="g",offset=-1},
		{from="W",to="o",offset=-1},
		{from="W",to="q",offset=-1},
		{from="W",to="s",offset=-1},
		{from="W",to="z",offset=-1},
		{from="W",to="À",offset=-1},
		{from="W",to="Á",offset=-1},
		{from="W",to="Â",offset=-1},
		{from="W",to="Ã",offset=-1},
		{from="W",to="Ä",offset=-1},
		{from="W",to="Å",offset=-1},
		{from="W",to="Æ",offset=-1},
		{from="W",to="Ý",offset=1},
		{from="W",to="æ",offset=-1},
		{from="W",to="ç",offset=-1},
		{from="W",to="è",offset=-1},
		{from="W",to="é",offset=-1},
		{from="W",to="ê",offset=-1},
		{from="W",to="ë",offset=-1},
		{from="W",to="ð",offset=-1},
		{from="W",to="ò",offset=-1},
		{from="W",to="ó",offset=-1},
		{from="W",to="ô",offset=-1},
		{from="W",to="õ",offset=-1},
		{from="W",to="ö",offset=-1},
		{from="W",to="ø",offset=-1},
		{from="W",to="þ",offset=1},
		{from="W",to="œ",offset=-1},
		{from="W",to="š",offset=-1},
		{from="W",to="Ÿ",offset=1},
		{from="W",to="ž",offset=-1},
		{from="X",to="-",offset=-1},
		{from="X",to="A",offset=1},
		{from="X",to="­",offset=-1},
		{from="X",to="À",offset=1},
		{from="X",to="Á",offset=1},
		{from="X",to="Â",offset=1},
		{from="X",to="Ã",offset=1},
		{from="X",to="Ä",offset=1},
		{from="X",to="Å",offset=1},
		{from="X",to="Æ",offset=1},
		{from="Y",to=",",offset=-1},
		{from="Y",to="-",offset=-1},
		{from="Y",to=".",offset=-1},
		{from="Y",to="/",offset=-1},
		{from="Y",to="4",offset=-1},
		{from="Y",to="V",offset=1},
		{from="Y",to="W",offset=1},
		{from="Y",to="a",offset=-1},
		{from="Y",to="c",offset=-1},
		{from="Y",to="d",offset=-1},
		{from="Y",to="e",offset=-1},
		{from="Y",to="g",offset=-1},
		{from="Y",to="m",offset=-1},
		{from="Y",to="n",offset=-1},
		{from="Y",to="o",offset=-1},
		{from="Y",to="p",offset=-1},
		{from="Y",to="q",offset=-1},
		{from="Y",to="r",offset=-1},
		{from="Y",to="s",offset=-1},
		{from="Y",to="u",offset=-1},
		{from="Y",to="v",offset=-1},
		{from="Y",to="w",offset=-1},
		{from="Y",to="x",offset=-1},
		{from="Y",to="y",offset=-1},
		{from="Y",to="z",offset=-1},
		{from="Y",to="«",offset=-1},
		{from="Y",to="­",offset=-1},
		{from="Y",to="Æ",offset=-1},
		{from="Y",to="Ý",offset=1},
		{from="Y",to="à",offset=-1},
		{from="Y",to="á",offset=-1},
		{from="Y",to="â",offset=-1},
		{from="Y",to="ã",offset=-1},
		{from="Y",to="ä",offset=-1},
		{from="Y",to="å",offset=-1},
		{from="Y",to="æ",offset=-1},
		{from="Y",to="ç",offset=-1},
		{from="Y",to="è",offset=-1},
		{from="Y",to="é",offset=-1},
		{from="Y",to="ê",offset=-1},
		{from="Y",to="ë",offset=-1},
		{from="Y",to="ð",offset=-1},
		{from="Y",to="ñ",offset=-1},
		{from="Y",to="ò",offset=-1},
		{from="Y",to="ó",offset=-1},
		{from="Y",to="ô",offset=-1},
		{from="Y",to="õ",offset=-1},
		{from="Y",to="ö",offset=-1},
		{from="Y",to="ø",offset=-1},
		{from="Y",to="ù",offset=-1},
		{from="Y",to="ú",offset=-1},
		{from="Y",to="û",offset=-1},
		{from="Y",to="ü",offset=-1},
		{from="Y",to="ý",offset=-1},
		{from="Y",to="ÿ",offset=-1},
		{from="Y",to="œ",offset=-1},
		{from="Y",to="š",offset=-1},
		{from="Y",to="Ÿ",offset=1},
		{from="Y",to="ž",offset=-1},
		{from="[",to="4",offset=-1},
		{from="[",to="C",offset=-1},
		{from="[",to="G",offset=-1},
		{from="[",to="O",offset=-1},
		{from="[",to="Q",offset=-1},
		{from="[",to="a",offset=-1},
		{from="[",to="c",offset=-1},
		{from="[",to="d",offset=-1},
		{from="[",to="e",offset=-1},
		{from="[",to="j",offset=2},
		{from="[",to="m",offset=-1},
		{from="[",to="n",offset=-1},
		{from="[",to="o",offset=-1},
		{from="[",to="q",offset=-1},
		{from="[",to="r",offset=-1},
		{from="[",to="s",offset=-1},
		{from="[",to="t",offset=-1},
		{from="[",to="u",offset=-1},
		{from="[",to="v",offset=-1},
		{from="[",to="w",offset=-1},
		{from="[",to="z",offset=-1},
		{from="[",to="Ç",offset=-1},
		{from="[",to="Ò",offset=-1},
		{from="[",to="Ó",offset=-1},
		{from="[",to="Ô",offset=-1},
		{from="[",to="Õ",offset=-1},
		{from="[",to="Ö",offset=-1},
		{from="[",to="Ø",offset=-1},
		{from="[",to="à",offset=-1},
		{from="[",to="á",offset=-1},
		{from="[",to="â",offset=-1},
		{from="[",to="ã",offset=-1},
		{from="[",to="ä",offset=-1},
		{from="[",to="å",offset=-1},
		{from="[",to="æ",offset=-1},
		{from="[",to="ç",offset=-1},
		{from="[",to="è",offset=-1},
		{from="[",to="é",offset=-1},
		{from="[",to="ê",offset=-1},
		{from="[",to="ë",offset=-1},
		{from="[",to="ñ",offset=-1},
		{from="[",to="ò",offset=-1},
		{from="[",to="ó",offset=-1},
		{from="[",to="ô",offset=-1},
		{from="[",to="õ",offset=-1},
		{from="[",to="ö",offset=-1},
		{from="[",to="ø",offset=-1},
		{from="[",to="ù",offset=-1},
		{from="[",to="ú",offset=-1},
		{from="[",to="û",offset=-1},
		{from="[",to="ü",offset=-1},
		{from="[",to="Œ",offset=-1},
		{from="[",to="œ",offset=-1},
		{from="[",to="š",offset=-1},
		{from="[",to="ž",offset=-1},
		{from="\\",to='"',offset=-2},
		{from="\\",to="'",offset=-1},
		{from="\\",to="0",offset=-1},
		{from="\\",to="4",offset=-1},
		{from="\\",to="6",offset=-1},
		{from="\\",to="7",offset=-1},
		{from="\\",to="8",offset=-1},
		{from="\\",to="9",offset=-1},
		{from="\\",to="C",offset=-1},
		{from="\\",to="G",offset=-1},
		{from="\\",to="O",offset=-1},
		{from="\\",to="Q",offset=-1},
		{from="\\",to="T",offset=-1},
		{from="\\",to="U",offset=-1},
		{from="\\",to="V",offset=-1},
		{from="\\",to="W",offset=-1},
		{from="\\",to="Y",offset=-1},
		{from="\\",to="c",offset=-1},
		{from="\\",to="d",offset=-1},
		{from="\\",to="e",offset=-1},
		{from="\\",to="j",offset=1},
		{from="\\",to="o",offset=-1},
		{from="\\",to="q",offset=-1},
		{from="\\",to="t",offset=-1},
		{from="\\",to="u",offset=-1},
		{from="\\",to="v",offset=-1},
		{from="\\",to="w",offset=-1},
		{from="\\",to="Ç",offset=-1},
		{from="\\",to="Ò",offset=-1},
		{from="\\",to="Ó",offset=-1},
		{from="\\",to="Ô",offset=-1},
		{from="\\",to="Õ",offset=-1},
		{from="\\",to="Ö",offset=-1},
		{from="\\",to="Ø",offset=-1},
		{from="\\",to="Ù",offset=-1},
		{from="\\",to="Ú",offset=-1},
		{from="\\",to="Û",offset=-1},
		{from="\\",to="Ü",offset=-1},
		{from="\\",to="Ý",offset=-1},
		{from="\\",to="ç",offset=-1},
		{from="\\",to="è",offset=-1},
		{from="\\",to="é",offset=-1},
		{from="\\",to="ê",offset=-1},
		{from="\\",to="ë",offset=-1},
		{from="\\",to="ð",offset=-1},
		{from="\\",to="ò",offset=-1},
		{from="\\",to="ó",offset=-1},
		{from="\\",to="ô",offset=-1},
		{from="\\",to="õ",offset=-1},
		{from="\\",to="ö",offset=-1},
		{from="\\",to="ø",offset=-1},
		{from="\\",to="ù",offset=-1},
		{from="\\",to="ú",offset=-1},
		{from="\\",to="û",offset=-1},
		{from="\\",to="ü",offset=-1},
		{from="\\",to="Œ",offset=-1},
		{from="\\",to="œ",offset=-1},
		{from="\\",to="Ÿ",offset=-1},
		{from="a",to="T",offset=-1},
		{from="a",to="V",offset=-1},
		{from="a",to="W",offset=-1},
		{from="a",to="Y",offset=-1},
		{from="a",to="\\",offset=-1},
		{from="a",to="]",offset=-1},
		{from="a",to="Ý",offset=-1},
		{from="a",to="Ÿ",offset=-1},
		{from="b",to=")",offset=-1},
		{from="b",to="/",offset=-1},
		{from="b",to="W",offset=-1},
		{from="b",to="X",offset=-1},
		{from="b",to="Y",offset=-1},
		{from="b",to="\\",offset=-1},
		{from="b",to="]",offset=-1},
		{from="b",to="Ý",offset=-1},
		{from="b",to="Ÿ",offset=-1},
		{from="c",to="V",offset=-1},
		{from="c",to="Y",offset=-1},
		{from="c",to="]",offset=-1},
		{from="c",to="Ý",offset=-1},
		{from="c",to="Ÿ",offset=-1},
		{from="e",to="/",offset=-1},
		{from="e",to="T",offset=-1},
		{from="e",to="V",offset=-1},
		{from="e",to="Y",offset=-1},
		{from="e",to="\\",offset=-1},
		{from="e",to="]",offset=-1},
		{from="e",to="Ý",offset=-1},
		{from="e",to="Ÿ",offset=-1},
		{from="f",to='"',offset=1},
		{from="f",to="'",offset=1},
		{from="f",to=")",offset=1},
		{from="f",to="H",offset=1},
		{from="f",to="J",offset=1},
		{from="f",to="M",offset=1},
		{from="f",to="T",offset=1},
		{from="f",to="U",offset=1},
		{from="f",to="V",offset=1},
		{from="f",to="W",offset=1},
		{from="f",to="X",offset=1},
		{from="f",to="Y",offset=1},
		{from="f",to="\\",offset=1},
		{from="f",to="]",offset=1},
		{from="f",to="b",offset=2},
		{from="f",to="h",offset=1},
		{from="f",to="j",offset=1},
		{from="f",to="k",offset=1},
		{from="f",to="l",offset=1},
		{from="f",to="}",offset=1},
		{from="f",to="Ù",offset=1},
		{from="f",to="Ú",offset=1},
		{from="f",to="Û",offset=1},
		{from="f",to="Ü",offset=1},
		{from="f",to="Ý",offset=1},
		{from="f",to="ì",offset=1},
		{from="f",to="ï",offset=1},
		{from="f",to="þ",offset=2},
		{from="f",to="ł",offset=1},
		{from="f",to="Ÿ",offset=1},
		{from="g",to="*",offset=1},
		{from="g",to="f",offset=1},
		{from="g",to="j",offset=1},
		{from="g",to="ß",offset=1},
		{from="h",to="7",offset=-1},
		{from="h",to="T",offset=-1},
		{from="h",to="V",offset=-1},
		{from="h",to="W",offset=-1},
		{from="h",to="Y",offset=-1},
		{from="h",to="\\",offset=-1},
		{from="h",to="]",offset=-1},
		{from="h",to="Ý",offset=-1},
		{from="h",to="Ÿ",offset=-1},
		{from="k",to="Y",offset=-1},
		{from="k",to="Ý",offset=-1},
		{from="k",to="Ÿ",offset=-1},
		{from="l",to="·",offset=-1},
		{from="m",to="T",offset=-1},
		{from="m",to="V",offset=-1},
		{from="m",to="W",offset=-1},
		{from="m",to="Y",offset=-1},
		{from="m",to="\\",offset=-1},
		{from="m",to="]",offset=-1},
		{from="m",to="Ý",offset=-1},
		{from="m",to="Ÿ",offset=-1},
		{from="n",to="T",offset=-1},
		{from="n",to="V",offset=-1},
		{from="n",to="W",offset=-1},
		{from="n",to="Y",offset=-1},
		{from="n",to="\\",offset=-1},
		{from="n",to="]",offset=-1},
		{from="n",to="Ý",offset=-1},
		{from="n",to="Ÿ",offset=-1},
		{from="o",to=")",offset=-1},
		{from="o",to="/",offset=-1},
		{from="o",to="T",offset=-1},
		{from="o",to="W",offset=-1},
		{from="o",to="X",offset=-1},
		{from="o",to="Y",offset=-1},
		{from="o",to="\\",offset=-1},
		{from="o",to="]",offset=-1},
		{from="o",to="Ý",offset=-1},
		{from="o",to="Ÿ",offset=-1},
		{from="p",to=")",offset=-1},
		{from="p",to="/",offset=-1},
		{from="p",to="T",offset=-1},
		{from="p",to="W",offset=-1},
		{from="p",to="X",offset=-1},
		{from="p",to="Y",offset=-1},
		{from="p",to="\\",offset=-1},
		{from="p",to="]",offset=-1},
		{from="p",to="Ý",offset=-1},
		{from="p",to="Ÿ",offset=-1},
		{from="q",to="V",offset=-1},
		{from="q",to="W",offset=-1},
		{from="q",to="Y",offset=-1},
		{from="q",to="j",offset=1},
		{from="q",to="Ý",offset=-1},
		{from="q",to="Ÿ",offset=-1},
		{from="r",to=",",offset=-1},
		{from="r",to=".",offset=-1},
		{from="r",to="/",offset=-1},
		{from="r",to="X",offset=-1},
		{from="r",to="Y",offset=-1},
		{from="r",to="]",offset=-1},
		{from="r",to="Ý",offset=-1},
		{from="r",to="Ÿ",offset=-1},
		{from="s",to="W",offset=-1},
		{from="s",to="Y",offset=-1},
		{from="s",to="]",offset=-1},
		{from="s",to="Ý",offset=-1},
		{from="s",to="Ÿ",offset=-1},
		{from="t",to="Y",offset=-1},
		{from="t",to="Ý",offset=-1},
		{from="t",to="Ÿ",offset=-1},
		{from="u",to="V",offset=-1},
		{from="u",to="W",offset=-1},
		{from="u",to="Y",offset=-1},
		{from="u",to="\\",offset=-1},
		{from="u",to="]",offset=-1},
		{from="u",to="Ý",offset=-1},
		{from="u",to="Ÿ",offset=-1},
		{from="v",to=",",offset=-1},
		{from="v",to=".",offset=-1},
		{from="v",to="/",offset=-1},
		{from="v",to="A",offset=-1},
		{from="v",to="J",offset=-1},
		{from="v",to="X",offset=-1},
		{from="v",to="]",offset=-1},
		{from="v",to="À",offset=-1},
		{from="v",to="Á",offset=-1},
		{from="v",to="Â",offset=-1},
		{from="v",to="Ã",offset=-1},
		{from="v",to="Ä",offset=-1},
		{from="v",to="Å",offset=-1},
		{from="w",to=",",offset=-1},
		{from="w",to=".",offset=-1},
		{from="w",to="/",offset=-1},
		{from="w",to="A",offset=-1},
		{from="w",to="J",offset=-1},
		{from="w",to="X",offset=-1},
		{from="w",to="]",offset=-1},
		{from="w",to="À",offset=-1},
		{from="w",to="Á",offset=-1},
		{from="w",to="Â",offset=-1},
		{from="w",to="Ã",offset=-1},
		{from="w",to="Ä",offset=-1},
		{from="w",to="Å",offset=-1},
		{from="x",to="Y",offset=-1},
		{from="x",to="Ý",offset=-1},
		{from="x",to="Ÿ",offset=-1},
		{from="y",to=",",offset=-1},
		{from="y",to=".",offset=-1},
		{from="y",to="/",offset=-1},
		{from="y",to="A",offset=-1},
		{from="y",to="J",offset=-1},
		{from="y",to="]",offset=-1},
		{from="y",to="À",offset=-1},
		{from="y",to="Á",offset=-1},
		{from="y",to="Â",offset=-1},
		{from="y",to="Ã",offset=-1},
		{from="y",to="Ä",offset=-1},
		{from="y",to="Å",offset=-1},
		{from="z",to="V",offset=-1},
		{from="z",to="W",offset=-1},
		{from="z",to="Y",offset=-1},
		{from="z",to="]",offset=-1},
		{from="z",to="Ý",offset=-1},
		{from="z",to="Ÿ",offset=-1},
		{from="{",to="j",offset=1},
		{from="|",to="j",offset=1},
		{from="¡",to="j",offset=1},
		{from="·",to="7",offset=-1},
		{from="·",to="l",offset=-1},
		{from="·",to="ł",offset=-1},
		{from="»",to='"',offset=-1},
		{from="»",to="'",offset=-1},
		{from="»",to="T",offset=-1},
		{from="»",to="Y",offset=-1},
		{from="»",to="Ý",offset=-1},
		{from="»",to="Ÿ",offset=-1},
		{from="¿",to="V",offset=-1},
		{from="¿",to="W",offset=-1},
		{from="¿",to="Y",offset=-1},
		{from="¿",to="Ý",offset=-1},
		{from="¿",to="Ÿ",offset=-1},
		{from="À",to='"',offset=-1},
		{from="À",to="'",offset=-1},
		{from="À",to="A",offset=1},
		{from="À",to="J",offset=1},
		{from="À",to="V",offset=-1},
		{from="À",to="W",offset=-1},
		{from="À",to="X",offset=1},
		{from="À",to="\\",offset=-1},
		{from="À",to="´",offset=-1},
		{from="À",to="Á",offset=1},
		{from="À",to="Â",offset=1},
		{from="À",to="Ã",offset=1},
		{from="À",to="Ä",offset=1},
		{from="À",to="Å",offset=1},
		{from="À",to="Æ",offset=1},
		{from="Á",to='"',offset=-1},
		{from="Á",to="'",offset=-1},
		{from="Á",to="A",offset=1},
		{from="Á",to="J",offset=1},
		{from="Á",to="V",offset=-1},
		{from="Á",to="W",offset=-1},
		{from="Á",to="X",offset=1},
		{from="Á",to="\\",offset=-1},
		{from="Á",to="´",offset=-1},
		{from="Á",to="À",offset=1},
		{from="Á",to="Â",offset=1},
		{from="Á",to="Ã",offset=1},
		{from="Á",to="Ä",offset=1},
		{from="Á",to="Å",offset=1},
		{from="Á",to="Æ",offset=1},
		{from="Â",to='"',offset=-1},
		{from="Â",to="'",offset=-1},
		{from="Â",to="A",offset=1},
		{from="Â",to="J",offset=1},
		{from="Â",to="V",offset=-1},
		{from="Â",to="W",offset=-1},
		{from="Â",to="X",offset=1},
		{from="Â",to="\\",offset=-1},
		{from="Â",to="´",offset=-1},
		{from="Â",to="À",offset=1},
		{from="Â",to="Á",offset=1},
		{from="Â",to="Ã",offset=1},
		{from="Â",to="Ä",offset=1},
		{from="Â",to="Å",offset=1},
		{from="Â",to="Æ",offset=1},
		{from="Ã",to='"',offset=-1},
		{from="Ã",to="'",offset=-1},
		{from="Ã",to="A",offset=1},
		{from="Ã",to="J",offset=1},
		{from="Ã",to="V",offset=-1},
		{from="Ã",to="W",offset=-1},
		{from="Ã",to="X",offset=1},
		{from="Ã",to="\\",offset=-1},
		{from="Ã",to="´",offset=-1},
		{from="Ã",to="À",offset=1},
		{from="Ã",to="Á",offset=1},
		{from="Ã",to="Â",offset=1},
		{from="Ã",to="Ä",offset=1},
		{from="Ã",to="Å",offset=1},
		{from="Ã",to="Æ",offset=1},
		{from="Ä",to='"',offset=-1},
		{from="Ä",to="'",offset=-1},
		{from="Ä",to="A",offset=1},
		{from="Ä",to="J",offset=1},
		{from="Ä",to="V",offset=-1},
		{from="Ä",to="W",offset=-1},
		{from="Ä",to="X",offset=1},
		{from="Ä",to="\\",offset=-1},
		{from="Ä",to="´",offset=-1},
		{from="Ä",to="À",offset=1},
		{from="Ä",to="Á",offset=1},
		{from="Ä",to="Â",offset=1},
		{from="Ä",to="Ã",offset=1},
		{from="Ä",to="Å",offset=1},
		{from="Ä",to="Æ",offset=1},
		{from="Å",to='"',offset=-1},
		{from="Å",to="'",offset=-1},
		{from="Å",to="A",offset=1},
		{from="Å",to="J",offset=1},
		{from="Å",to="V",offset=-1},
		{from="Å",to="W",offset=-1},
		{from="Å",to="X",offset=1},
		{from="Å",to="\\",offset=-1},
		{from="Å",to="´",offset=-1},
		{from="Å",to="À",offset=1},
		{from="Å",to="Á",offset=1},
		{from="Å",to="Â",offset=1},
		{from="Å",to="Ã",offset=1},
		{from="Å",to="Ä",offset=1},
		{from="Å",to="Æ",offset=1},
		{from="Ð",to="/",offset=-1},
		{from="Ð",to="]",offset=-1},
		{from="Ð",to="Æ",offset=-1},
		{from="Ñ",to="/",offset=-1},
		{from="Ò",to="/",offset=-1},
		{from="Ò",to="]",offset=-1},
		{from="Ò",to="Æ",offset=-1},
		{from="Ó",to="/",offset=-1},
		{from="Ó",to="]",offset=-1},
		{from="Ó",to="Æ",offset=-1},
		{from="Ô",to="/",offset=-1},
		{from="Ô",to="]",offset=-1},
		{from="Ô",to="Æ",offset=-1},
		{from="Õ",to="/",offset=-1},
		{from="Õ",to="]",offset=-1},
		{from="Õ",to="Æ",offset=-1},
		{from="Ö",to="/",offset=-1},
		{from="Ö",to="]",offset=-1},
		{from="Ö",to="Æ",offset=-1},
		{from="Ø",to="/",offset=-1},
		{from="Ø",to="]",offset=-1},
		{from="Ø",to="Æ",offset=-1},
		{from="Ù",to=",",offset=-1},
		{from="Ù",to="/",offset=-1},
		{from="Ù",to="Æ",offset=-1},
		{from="Ú",to=",",offset=-1},
		{from="Ú",to="/",offset=-1},
		{from="Ú",to="Æ",offset=-1},
		{from="Û",to=",",offset=-1},
		{from="Û",to="/",offset=-1},
		{from="Û",to="Æ",offset=-1},
		{from="Ü",to=",",offset=-1},
		{from="Ü",to="/",offset=-1},
		{from="Ü",to="Æ",offset=-1},
		{from="Ý",to=",",offset=-1},
		{from="Ý",to="-",offset=-1},
		{from="Ý",to=".",offset=-1},
		{from="Ý",to="/",offset=-1},
		{from="Ý",to="4",offset=-1},
		{from="Ý",to="V",offset=1},
		{from="Ý",to="W",offset=1},
		{from="Ý",to="Y",offset=1},
		{from="Ý",to="a",offset=-1},
		{from="Ý",to="c",offset=-1},
		{from="Ý",to="d",offset=-1},
		{from="Ý",to="e",offset=-1},
		{from="Ý",to="g",offset=-1},
		{from="Ý",to="m",offset=-1},
		{from="Ý",to="n",offset=-1},
		{from="Ý",to="o",offset=-1},
		{from="Ý",to="p",offset=-1},
		{from="Ý",to="q",offset=-1},
		{from="Ý",to="r",offset=-1},
		{from="Ý",to="s",offset=-1},
		{from="Ý",to="u",offset=-1},
		{from="Ý",to="v",offset=-1},
		{from="Ý",to="w",offset=-1},
		{from="Ý",to="x",offset=-1},
		{from="Ý",to="y",offset=-1},
		{from="Ý",to="z",offset=-1},
		{from="Ý",to="«",offset=-1},
		{from="Ý",to="­",offset=-1},
		{from="Ý",to="Æ",offset=-1},
		{from="Ý",to="à",offset=-1},
		{from="Ý",to="á",offset=-1},
		{from="Ý",to="â",offset=-1},
		{from="Ý",to="ã",offset=-1},
		{from="Ý",to="ä",offset=-1},
		{from="Ý",to="å",offset=-1},
		{from="Ý",to="æ",offset=-1},
		{from="Ý",to="ç",offset=-1},
		{from="Ý",to="è",offset=-1},
		{from="Ý",to="é",offset=-1},
		{from="Ý",to="ê",offset=-1},
		{from="Ý",to="ë",offset=-1},
		{from="Ý",to="ð",offset=-1},
		{from="Ý",to="ñ",offset=-1},
		{from="Ý",to="ò",offset=-1},
		{from="Ý",to="ó",offset=-1},
		{from="Ý",to="ô",offset=-1},
		{from="Ý",to="õ",offset=-1},
		{from="Ý",to="ö",offset=-1},
		{from="Ý",to="ø",offset=-1},
		{from="Ý",to="ù",offset=-1},
		{from="Ý",to="ú",offset=-1},
		{from="Ý",to="û",offset=-1},
		{from="Ý",to="ü",offset=-1},
		{from="Ý",to="ý",offset=-1},
		{from="Ý",to="ÿ",offset=-1},
		{from="Ý",to="œ",offset=-1},
		{from="Ý",to="š",offset=-1},
		{from="Ý",to="Ÿ",offset=1},
		{from="Ý",to="ž",offset=-1},
		{from="Þ",to=",",offset=-1},
		{from="Þ",to=".",offset=-1},
		{from="Þ",to="/",offset=-1},
		{from="Þ",to="J",offset=-1},
		{from="Þ",to="X",offset=-1},
		{from="Þ",to="]",offset=-1},
		{from="Þ",to="Æ",offset=-1},
		{from="à",to="T",offset=-1},
		{from="à",to="V",offset=-1},
		{from="à",to="W",offset=-1},
		{from="à",to="Y",offset=-1},
		{from="à",to="\\",offset=-1},
		{from="à",to="]",offset=-1},
		{from="à",to="Ý",offset=-1},
		{from="à",to="Ÿ",offset=-1},
		{from="á",to="T",offset=-1},
		{from="á",to="V",offset=-1},
		{from="á",to="W",offset=-1},
		{from="á",to="Y",offset=-1},
		{from="á",to="\\",offset=-1},
		{from="á",to="]",offset=-1},
		{from="á",to="Ý",offset=-1},
		{from="á",to="Ÿ",offset=-1},
		{from="â",to="T",offset=-1},
		{from="â",to="V",offset=-1},
		{from="â",to="W",offset=-1},
		{from="â",to="Y",offset=-1},
		{from="â",to="\\",offset=-1},
		{from="â",to="]",offset=-1},
		{from="â",to="Ý",offset=-1},
		{from="â",to="Ÿ",offset=-1},
		{from="ã",to="T",offset=-1},
		{from="ã",to="V",offset=-1},
		{from="ã",to="W",offset=-1},
		{from="ã",to="Y",offset=-1},
		{from="ã",to="\\",offset=-1},
		{from="ã",to="]",offset=-1},
		{from="ã",to="Ý",offset=-1},
		{from="ã",to="Ÿ",offset=-1},
		{from="ä",to="T",offset=-1},
		{from="ä",to="V",offset=-1},
		{from="ä",to="W",offset=-1},
		{from="ä",to="Y",offset=-1},
		{from="ä",to="\\",offset=-1},
		{from="ä",to="]",offset=-1},
		{from="ä",to="Ý",offset=-1},
		{from="ä",to="Ÿ",offset=-1},
		{from="å",to="T",offset=-1},
		{from="å",to="V",offset=-1},
		{from="å",to="W",offset=-1},
		{from="å",to="Y",offset=-1},
		{from="å",to="\\",offset=-1},
		{from="å",to="]",offset=-1},
		{from="å",to="Ý",offset=-1},
		{from="å",to="Ÿ",offset=-1},
		{from="æ",to="/",offset=-1},
		{from="æ",to="T",offset=-1},
		{from="æ",to="V",offset=-1},
		{from="æ",to="Y",offset=-1},
		{from="æ",to="\\",offset=-1},
		{from="æ",to="]",offset=-1},
		{from="æ",to="Ý",offset=-1},
		{from="æ",to="Ÿ",offset=-1},
		{from="ç",to="V",offset=-1},
		{from="ç",to="Y",offset=-1},
		{from="ç",to="]",offset=-1},
		{from="ç",to="Ý",offset=-1},
		{from="ç",to="Ÿ",offset=-1},
		{from="è",to="/",offset=-1},
		{from="è",to="T",offset=-1},
		{from="è",to="V",offset=-1},
		{from="è",to="Y",offset=-1},
		{from="è",to="\\",offset=-1},
		{from="è",to="]",offset=-1},
		{from="è",to="Ý",offset=-1},
		{from="è",to="Ÿ",offset=-1},
		{from="é",to="/",offset=-1},
		{from="é",to="T",offset=-1},
		{from="é",to="V",offset=-1},
		{from="é",to="Y",offset=-1},
		{from="é",to="\\",offset=-1},
		{from="é",to="]",offset=-1},
		{from="é",to="Ý",offset=-1},
		{from="é",to="Ÿ",offset=-1},
		{from="ê",to="/",offset=-1},
		{from="ê",to="T",offset=-1},
		{from="ê",to="V",offset=-1},
		{from="ê",to="Y",offset=-1},
		{from="ê",to="\\",offset=-1},
		{from="ê",to="]",offset=-1},
		{from="ê",to="Ý",offset=-1},
		{from="ê",to="Ÿ",offset=-1},
		{from="ë",to="/",offset=-1},
		{from="ë",to="T",offset=-1},
		{from="ë",to="V",offset=-1},
		{from="ë",to="Y",offset=-1},
		{from="ë",to="\\",offset=-1},
		{from="ë",to="]",offset=-1},
		{from="ë",to="Ý",offset=-1},
		{from="ë",to="Ÿ",offset=-1},
		{from="î",to="V",offset=1},
		{from="ð",to="/",offset=-1},
		{from="ð",to="]",offset=-1},
		{from="ñ",to="T",offset=-1},
		{from="ñ",to="V",offset=-1},
		{from="ñ",to="W",offset=-1},
		{from="ñ",to="Y",offset=-1},
		{from="ñ",to="\\",offset=-1},
		{from="ñ",to="]",offset=-1},
		{from="ñ",to="Ý",offset=-1},
		{from="ñ",to="Ÿ",offset=-1},
		{from="ò",to=")",offset=-1},
		{from="ò",to="/",offset=-1},
		{from="ò",to="T",offset=-1},
		{from="ò",to="W",offset=-1},
		{from="ò",to="X",offset=-1},
		{from="ò",to="Y",offset=-1},
		{from="ò",to="\\",offset=-1},
		{from="ò",to="]",offset=-1},
		{from="ò",to="Ý",offset=-1},
		{from="ò",to="Ÿ",offset=-1},
		{from="ó",to=")",offset=-1},
		{from="ó",to="/",offset=-1},
		{from="ó",to="T",offset=-1},
		{from="ó",to="W",offset=-1},
		{from="ó",to="X",offset=-1},
		{from="ó",to="Y",offset=-1},
		{from="ó",to="\\",offset=-1},
		{from="ó",to="]",offset=-1},
		{from="ó",to="Ý",offset=-1},
		{from="ó",to="Ÿ",offset=-1},
		{from="ô",to=")",offset=-1},
		{from="ô",to="/",offset=-1},
		{from="ô",to="T",offset=-1},
		{from="ô",to="W",offset=-1},
		{from="ô",to="X",offset=-1},
		{from="ô",to="Y",offset=-1},
		{from="ô",to="\\",offset=-1},
		{from="ô",to="]",offset=-1},
		{from="ô",to="Ý",offset=-1},
		{from="ô",to="Ÿ",offset=-1},
		{from="õ",to=")",offset=-1},
		{from="õ",to="/",offset=-1},
		{from="õ",to="T",offset=-1},
		{from="õ",to="W",offset=-1},
		{from="õ",to="X",offset=-1},
		{from="õ",to="Y",offset=-1},
		{from="õ",to="\\",offset=-1},
		{from="õ",to="]",offset=-1},
		{from="õ",to="Ý",offset=-1},
		{from="õ",to="Ÿ",offset=-1},
		{from="ö",to=")",offset=-1},
		{from="ö",to="/",offset=-1},
		{from="ö",to="T",offset=-1},
		{from="ö",to="W",offset=-1},
		{from="ö",to="X",offset=-1},
		{from="ö",to="Y",offset=-1},
		{from="ö",to="\\",offset=-1},
		{from="ö",to="]",offset=-1},
		{from="ö",to="Ý",offset=-1},
		{from="ö",to="Ÿ",offset=-1},
		{from="ø",to=")",offset=-1},
		{from="ø",to="/",offset=-1},
		{from="ø",to="T",offset=-1},
		{from="ø",to="W",offset=-1},
		{from="ø",to="X",offset=-1},
		{from="ø",to="Y",offset=-1},
		{from="ø",to="\\",offset=-1},
		{from="ø",to="]",offset=-1},
		{from="ø",to="Ý",offset=-1},
		{from="ø",to="Ÿ",offset=-1},
		{from="ù",to="V",offset=-1},
		{from="ù",to="W",offset=-1},
		{from="ù",to="Y",offset=-1},
		{from="ù",to="\\",offset=-1},
		{from="ù",to="]",offset=-1},
		{from="ù",to="Ý",offset=-1},
		{from="ù",to="Ÿ",offset=-1},
		{from="ú",to="V",offset=-1},
		{from="ú",to="W",offset=-1},
		{from="ú",to="Y",offset=-1},
		{from="ú",to="\\",offset=-1},
		{from="ú",to="]",offset=-1},
		{from="ú",to="Ý",offset=-1},
		{from="ú",to="Ÿ",offset=-1},
		{from="û",to="V",offset=-1},
		{from="û",to="W",offset=-1},
		{from="û",to="Y",offset=-1},
		{from="û",to="\\",offset=-1},
		{from="û",to="]",offset=-1},
		{from="û",to="Ý",offset=-1},
		{from="û",to="Ÿ",offset=-1},
		{from="ü",to="V",offset=-1},
		{from="ü",to="W",offset=-1},
		{from="ü",to="Y",offset=-1},
		{from="ü",to="\\",offset=-1},
		{from="ü",to="]",offset=-1},
		{from="ü",to="Ý",offset=-1},
		{from="ü",to="Ÿ",offset=-1},
		{from="ý",to=",",offset=-1},
		{from="ý",to=".",offset=-1},
		{from="ý",to="/",offset=-1},
		{from="ý",to="A",offset=-1},
		{from="ý",to="J",offset=-1},
		{from="ý",to="]",offset=-1},
		{from="ý",to="À",offset=-1},
		{from="ý",to="Á",offset=-1},
		{from="ý",to="Â",offset=-1},
		{from="ý",to="Ã",offset=-1},
		{from="ý",to="Ä",offset=-1},
		{from="ý",to="Å",offset=-1},
		{from="þ",to=")",offset=-1},
		{from="þ",to="/",offset=-1},
		{from="þ",to="T",offset=-1},
		{from="þ",to="W",offset=-1},
		{from="þ",to="X",offset=-1},
		{from="þ",to="Y",offset=-1},
		{from="þ",to="\\",offset=-1},
		{from="þ",to="]",offset=-1},
		{from="þ",to="Ý",offset=-1},
		{from="þ",to="Ÿ",offset=-1},
		{from="ÿ",to=",",offset=-1},
		{from="ÿ",to=".",offset=-1},
		{from="ÿ",to="/",offset=-1},
		{from="ÿ",to="A",offset=-1},
		{from="ÿ",to="J",offset=-1},
		{from="ÿ",to="]",offset=-1},
		{from="ÿ",to="À",offset=-1},
		{from="ÿ",to="Á",offset=-1},
		{from="ÿ",to="Â",offset=-1},
		{from="ÿ",to="Ã",offset=-1},
		{from="ÿ",to="Ä",offset=-1},
		{from="ÿ",to="Å",offset=-1},
		{from="Ł",to='"',offset=-1},
		{from="Ł",to="'",offset=-1},
		{from="Ł",to="*",offset=-1},
		{from="Ł",to="-",offset=-1},
		{from="Ł",to="T",offset=-1},
		{from="Ł",to="V",offset=-1},
		{from="Ł",to="W",offset=-1},
		{from="Ł",to="Y",offset=-1},
		{from="Ł",to="\\",offset=-1},
		{from="Ł",to="]",offset=-1},
		{from="Ł",to="v",offset=-1},
		{from="Ł",to="w",offset=-1},
		{from="Ł",to="ª",offset=-1},
		{from="Ł",to="­",offset=-1},
		{from="Ł",to="·",offset=-2},
		{from="Ł",to="Ý",offset=-1},
		{from="Ł",to="Ÿ",offset=-1},
		{from="ł",to="·",offset=-1},
		{from="œ",to="/",offset=-1},
		{from="œ",to="T",offset=-1},
		{from="œ",to="V",offset=-1},
		{from="œ",to="Y",offset=-1},
		{from="œ",to="\\",offset=-1},
		{from="œ",to="]",offset=-1},
		{from="œ",to="Ý",offset=-1},
		{from="œ",to="Ÿ",offset=-1},
		{from="Š",to="/",offset=-1},
		{from="š",to="W",offset=-1},
		{from="š",to="Y",offset=-1},
		{from="š",to="]",offset=-1},
		{from="š",to="Ý",offset=-1},
		{from="š",to="Ÿ",offset=-1},
		{from="Ÿ",to=",",offset=-1},
		{from="Ÿ",to="-",offset=-1},
		{from="Ÿ",to=".",offset=-1},
		{from="Ÿ",to="/",offset=-1},
		{from="Ÿ",to="4",offset=-1},
		{from="Ÿ",to="V",offset=1},
		{from="Ÿ",to="W",offset=1},
		{from="Ÿ",to="Y",offset=1},
		{from="Ÿ",to="a",offset=-1},
		{from="Ÿ",to="c",offset=-1},
		{from="Ÿ",to="d",offset=-1},
		{from="Ÿ",to="e",offset=-1},
		{from="Ÿ",to="g",offset=-1},
		{from="Ÿ",to="m",offset=-1},
		{from="Ÿ",to="n",offset=-1},
		{from="Ÿ",to="o",offset=-1},
		{from="Ÿ",to="p",offset=-1},
		{from="Ÿ",to="q",offset=-1},
		{from="Ÿ",to="r",offset=-1},
		{from="Ÿ",to="s",offset=-1},
		{from="Ÿ",to="u",offset=-1},
		{from="Ÿ",to="v",offset=-1},
		{from="Ÿ",to="w",offset=-1},
		{from="Ÿ",to="x",offset=-1},
		{from="Ÿ",to="y",offset=-1},
		{from="Ÿ",to="z",offset=-1},
		{from="Ÿ",to="«",offset=-1},
		{from="Ÿ",to="­",offset=-1},
		{from="Ÿ",to="Æ",offset=-1},
		{from="Ÿ",to="Ý",offset=1},
		{from="Ÿ",to="à",offset=-1},
		{from="Ÿ",to="á",offset=-1},
		{from="Ÿ",to="â",offset=-1},
		{from="Ÿ",to="ã",offset=-1},
		{from="Ÿ",to="ä",offset=-1},
		{from="Ÿ",to="å",offset=-1},
		{from="Ÿ",to="æ",offset=-1},
		{from="Ÿ",to="ç",offset=-1},
		{from="Ÿ",to="è",offset=-1},
		{from="Ÿ",to="é",offset=-1},
		{from="Ÿ",to="ê",offset=-1},
		{from="Ÿ",to="ë",offset=-1},
		{from="Ÿ",to="ð",offset=-1},
		{from="Ÿ",to="ñ",offset=-1},
		{from="Ÿ",to="ò",offset=-1},
		{from="Ÿ",to="ó",offset=-1},
		{from="Ÿ",to="ô",offset=-1},
		{from="Ÿ",to="õ",offset=-1},
		{from="Ÿ",to="ö",offset=-1},
		{from="Ÿ",to="ø",offset=-1},
		{from="Ÿ",to="ù",offset=-1},
		{from="Ÿ",to="ú",offset=-1},
		{from="Ÿ",to="û",offset=-1},
		{from="Ÿ",to="ü",offset=-1},
		{from="Ÿ",to="ý",offset=-1},
		{from="Ÿ",to="ÿ",offset=-1},
		{from="Ÿ",to="œ",offset=-1},
		{from="Ÿ",to="š",offset=-1},
		{from="Ÿ",to="ž",offset=-1},
		{from="ž",to="V",offset=-1},
		{from="ž",to="W",offset=-1},
		{from="ž",to="Y",offset=-1},
		{from="ž",to="]",offset=-1},
		{from="ž",to="Ý",offset=-1},
		{from="ž",to="Ÿ",offset=-1},
		{from="ƒ",to="H",offset=1},
	}
}
